### ISSUE TITLE
emu-docker licenses --accept does not always work

### ISSUE THREAD

**Issue by kneczaj** [google/android-emulator-container-scripts#108]
I see that often (not always) after I run `emu-docker licenses --accept` and then `emu-docker create` the second command asks me to confirm the licenses anyway.

**Comment by msimonin** [comment]
I faced the same issue. Looking at the code it seems that there is a race condition in the `accept_licenses` function (https://github.com/google/android-emulator-container-scripts/blob/2e9eaff0e561009a5d6b49933935239be3322740/emu/emu_docker.py#L39)

in pseudo-code it's doing something like:
```
to_accept = [License("android-sdk-license"), Licence("android-sdk-arm-dbt-license"), License("android-sdk-preview-license")]
for l in accept:
  l.accept()
```
license agreement is read/writen to `~/.config/emu-docker/goole-emu-docker.config`.
In the above the configuration file is read when building a License object, so each License object holds initially a representation of the configuration file which is empty then writes the agreement for the corresponding license which ... overwrite the previous write.

So the last call wins.

A temporary workaround would be to call as many times as license to accept.
