### ISSUE TITLE
ERROR : docker-compose -f js/docker/docker-compose.yaml up

### ISSUE THREAD

**Issue by camerony** [google/android-emulator-container-scripts#110]
Hi, 
 
I am probably missing something simple but I'm getting this error when trying to run compose both in venv or not.

Pulling front-envoy (emulator_envoy:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.``

**Comment by camerony** [comment]
there is a typo in your command in the Quick start, interactively creating and running a docker image of the README.md

docker-compose -f js/docker/docker-compose.yaml build
should be 
docker-compose -f js/docker/docker-compose-build.yaml build ?

but now i'm getting 
Step 5/6 : ADD certs/jwt_secrets_pub.jwks /etc/jwt_secrets_pub.jwks
ERROR: Service 'front-envoy' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder436324852/certs/jwt_secrets_pub.jwks: no such file or directory

**Comment by pokowaka** [comment]
Let me fix the typos and update the documentation. Creation of the containers should be done with the shell script instead. The shell script will binplace the proper files.
