### ISSUE TITLE
typo in run-with-gpu.sh

### ISSUE THREAD

**Issue by camerony** [google/android-emulator-container-scripts#111]
missing dash before TOKEN

`docker run --gpus all -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix  -e "TOKEN=$(cat ~/.emulator_console_auth_token)" -e "ADBKEY=$(cat ~/.android/adbkey)" -e "EMULATOR_PARAMS=-gpu host ${PARAMS}" --device /dev/kvm --publish 8556:8556/tcp --publish 5555:8555/tcp ${CONTAINER_ID}
`

**Comment by pokowaka** [comment]
Will fix.
