### ISSUE TITLE
setup.py pulls in jinja2-3.0 which seems to fail the emu-docker command

### ISSUE THREAD

**Issue by yagnasrinath** [google/android-emulator-container-scripts#122]
Since jinja2 version is not fixed, and jinja2 released 3.0 alpha, setup.py is downloading the alpha. This is causing the following failure:
```dirname = f"_jinja2-cache-{os.getuid()}"dirname = f"_jinja2-cache-{os.getuid()}"```

Forcing the jinja2 version to last stable version 2.11.1 in the setup.py here 
(jinja2==2.11.1) https://github.com/google/android-emulator-container-scripts/blob/master/setup.py#L125 , makes the error go away.

**Comment by pokowaka** [comment]
Thanks for letting us know, I will fix this.
