### ISSUE TITLE
ERROR:Failed to create default client, trying domain socket.

### ISSUE THREAD

**Issue by copiltembel** [google/android-emulator-container-scripts#124]
Just (re)installed Ubuntu 18.04.04 and I get the following error when running 

> emu-docker interactive --start

> ERROR:Failed to create default client, trying domain socket.
> Traceback (most recent call last):
>   File "/home/tdr/source/android-emulator-container-scripts/venv/lib/python3.6/site-packages/urllib3-1.25.8-py3.6.egg/urllib3/connectionpool.py", line 672, in urlopen
>     chunked=chunked,
>   File "/home/tdr/source/android-emulator-container-scripts/venv/lib/python3.6/site-packages/urllib3-1.25.8-py3.6.egg/urllib3/connectionpool.py", line 387, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.6/http/client.py", line 1254, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.6/http/client.py", line 974, in send
>     self.connect()
>   File "/home/tdr/source/android-emulator-container-scripts/venv/lib/python3.6/site-packages/docker-4.2.0-py3.6.egg/docker/transport/unixconn.py", line 43, in connect
>     sock.connect(self.unix_socket)
> PermissionError: [Errno 13] Permission denied

This seems to be a problem with python3 (I have Python 3.6.9), but I cannot upgrade it - ruined my Ubuntu installation. 

Any ideas for a workaround?

**Comment by pokowaka** [comment]
It looks like you are running into the permissions issues outlined [here](https://github.com/pokowaka/android-emulator-container-scripts/blob/master/TROUBLESHOOTING.md) 

The python client is trying to connect to docker, but it appears it doesn't have permission to do so. You can:

- Run everyhting as root.
- [Manager docker as non root](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user)
