### ISSUE TITLE
 Add support for AOA?

### ISSUE THREAD

**Issue by zangtian2** [google/android-emulator-container-scripts#126]
We make hardware to connect android phone through USB by AOA（Android Open Accessory Protocol）
But we found emulator not support，i rebuild source with kernel-dev （Device Drivers > USB Support > USB Modem (CDC ACM) support）。now still trying。Could support aoa in this tool。
Thank you very much.

**Comment by pokowaka** [comment]
I'm not sure what you mean. This tools is a wrapper around the android emulator.
