### ISSUE TITLE
Android Emulator package not found 

### ISSUE THREAD

**Issue by GauravP123** [google/android-emulator-container-scripts#131]
I am trying to setup an Android SDK  and run the emulator on [Amazon EC2 A1 Bare Metal Instance](https://aws.amazon.com/about-aws/whats-new/2019/10/introducing-availability-of-amazon-ec2-a1-bare-metal-instances/)

When I am trying to run following command 
`/opt/android-sdk/tools/bin/sdkmanager "emulator"
`
Getting error `Warning: Failed to find package emulator`

Then I am checking what all Packages are available to do that m running ` ./sdkmanager --list`
in this, it's not showing Emulator in Available Packages.

**Comment by pokowaka** [comment]
I'm not sure what you are trying to do. The package in this repository is for running the emulator inside a docker container, not outside. The readme provides instructions on how to get the emulator using docker.

**Comment by ngdangtu-vn** [comment]
@pokowaka Excuse me, but on NativeScript instruction, they recommends me to install "emulator" package without note for docker. Is that the doc's mistake or do we have any other way to do it?

**Comment by yowpark** [comment]
It may be an architecture issue. If the architecture is arm64, the emulator did not appear in the sdkmanager list.
