### ISSUE TITLE
How to enable sound?

### ISSUE THREAD

**Issue by danielmalmq** [google/android-emulator-container-scripts#133]
How can I enable the sound without sharing the hosts /dev/snd or similar?

**Comment by pokowaka** [comment]
This is not a scenario we have not yet covered completely. Let me do some investigation on how we can make this possible.

**Comment by danielmalmq** [comment]
Hey, any update on the issue? Or any hints as to how to solve it?

**Comment by pokowaka** [comment]
There are 2 ways to enable sound:

- See if it is possible through pulse audio. 
- Implement audio drivers in the WebRTC stack (this requires a lot of work)

The first one might be possible as described here:  https://github.com/mviereck/x11docker/wiki/Container-sound:-ALSA-or-Pulseaudio

The basic idea would be to configure a working pulse audio daemon through which the emulator will deliver sound.

**Comment by danielmalmq** [comment]
I see that you have added audio streaming in https://android-review.googlesource.com/c/platform/external/qemu/+/1310053 Can that be used to stream the audio over the goldfish webrtc link and if so do you have any hints as how to achieve this?

**Comment by pokowaka** [comment]
Yes this is possible, but will require some changes in our webrtc library. We are planning to:

- Upgrade webrtc to M83, which will reduce number of dependencies.
- Add support for audio through gRPC/Shared memory region.

Implementing audio directly from the gRPC endpoint might be possible, but might result in audio sync issues.

**Comment by danielmalmq** [comment]
Hey, just wondering what the status is of audio? I can see that the new webrtc m83 is added to emulator 30.0.15.

**Comment by henriklewander** [comment]
Hello, any news on audio implementation?

**Comment by pokowaka** [comment]
We are working on WebRTC audio support. I will link to the cl once we are closing in on enabling audio.

**Comment by pokowaka** [comment]
https://android-review.googlesource.com/c/platform/external/qemu/+/1354086

**Comment by henriklewander** [comment]
Thanks a lot for the update, looks very promising!
