### ISSUE TITLE
Set http_proxy not working

### ISSUE THREAD

**Issue by kavabunga6** [google/android-emulator-container-scripts#140]
Hi!
Me need forward all traffic from emulator on specific port (without restart), and i try this command:
`adb shell settings put global http_proxy "${proxy_host}:${proxy_port}"`

But:
When i try this command on emulator launched from studio - all working
When i try this command on emulator in docker - has no effect

How can I fix this?

Docker compose not used. Docker image created from interactive mode, not modified (26 O google_apis (x86_64) )

**Comment by pokowaka** [comment]
This has likely to do with docker and the value for ${proxy_host}.  The docker container has its own network environment and if ${proxy_host} is something like localhost it will not resolve to a connection outside of the container, resulting in unexpected behavior. 

If ${proxy_host} is localhost you might want to look at the follow [stackoverflow](https://stackoverflow.com/questions/24319662) question.

**Comment by kavabunga6** [comment]
> This has likely to do with docker and the value for ${proxy_host}. The docker container has its own network environment and if ${proxy_host} is something like localhost it will not resolve to a connection outside of the container, resulting in unexpected behavior.
> 
> If ${proxy_host} is localhost you might want to look at the following [stackoverflow](https://stackoverflow.com/questions/24319662) question.

Yes, we use localhost in ${proxy_host}
Thx for your help, I will check this [stackoverflow](https://stackoverflow.com/questions/24319662) ticket

**Comment by pokowaka** [comment]
Ok, let me know if I can close this issue. I can add an entry in the known issues/limitiations.
