### ISSUE TITLE
Two devices are exposed through adb instead of one

### ISSUE THREAD

**Issue by stephanepechard** [google/android-emulator-container-scripts#144]
Hi,

Once my docker stack is up and I connect to `localhost:5555` with `adb`, I get two devices exposed to it, i.e the command `adb devices` returns:

> List of devices attached
> emulator-5554   device
> localhost:5555  device

**Expected behaviour:** only one device is visible through `adb`, i.e having:

> List of devices attached
> emulator-5554   device

Thanks

**Comment by pokowaka** [comment]
It is possible that the local adb server detected the started container automatically. In that case there is no need to execute `adb connect localhost:5555`

**Comment by stephanepechard** [comment]
Right, this is the case, thanks!
Maybe a comment in the documentation could be useful to clarify that it may happen. Need a PR?

**Comment by pokowaka** [comment]
Yes, that indeed needs to happen. A PR is gladly accepted if you have one ready.
