### ISSUE TITLE
Unable to set Emulator FPS higher than 30

### ISSUE THREAD

**Issue by matoh** [google/android-emulator-container-scripts#149]
Hi, I would like to ask if it's possible to set max FPS for the Emulator through flag `rtcfps` according to the [added support](https://android.googlesource.com/platform/external/qemu/+/57ba2b3ecdd0231ffa521f38b69b614cb139932d).

I tried to set the flag, but I didn't succeeded to increase max FPS and the max FPS that I was able to reach was 30.
For testing I was using `AVD - Pixel2` with `hw.lcd.vsync: "60"`.

To change FPS from the client-side, I tried to apply Constraints in the video stream, when the stream with the track is ready in the following way:
```
let constraints = {
  frameRate: { 
    min: 60,
    max: 60 
  } 
};
			
stream.getTracks()[0].applyConstraints(constraints);
```
After calling applyConstraints I have received an error message: `Cannot satisfy constraints`. 
With FPS between [1..30] it works as expected.

Is there something more needed to be done to increate frameRate for the Emulator video stream?
Thanks

**Comment by pokowaka** [comment]
Newer versions of the emulator update frames as soon as they come in and configure the webrtc module to use 60 fps if possible.  What kind of hardware are you running the emulator under?  By default the emulator will use swiftshader, which might not be able produce frames fast enough. For example my macbook pro with swiftshader is unable to produce more than 26 fps.

**Comment by matoh** [comment]
Thanks for the info.

I was using AWS EC2 bare-metal - m5.metal.
