### ISSUE TITLE
after run-with-gpu.sh image, adb can not find the device

### ISSUE THREAD

**Issue by biwugang** [google/android-emulator-container-scripts#152]
hello.

I do test:
1. run-with-gpu.sh image (container start successfully)
2. adb connect localhost:5555
3. adb devices
but it does not list any devices

in run-with-gpu.sh it map local port 5555 to container port 8555, is it correct?
I think it should map 5555 to 5555.

after modify the port mapping and do test.
adb can find the devices

please check the port mapping in run-with-gpu.sh

**Comment by pokowaka** [comment]
Thank you for pointing this out.
