### ISSUE TITLE
Run emulator without KVM

### ISSUE THREAD

**Issue by number33** [google/android-emulator-container-scripts#160]
Is it possible to run the emulator without KVM?  And if so what changes would I need to do to make it work?

**Comment by pokowaka** [comment]
You can:

-  run arm only images. The performance will not be good and it is generally not recommended.
- remove  --device /dev/kvm from run.sh and  pass in the `-no-accel` flag and I.e. `./run.sh -no-accel` . This is not offically supported, and the performance will not be great.

**Comment by number33** [comment]
Thanks @pokowaka.

Where can I get a list of arm images to download?  `emu-docker list` shows `x86_64` images.

**Comment by pokowaka** [comment]
`emu-docker list --arm | grep arm`

Should list all the available arm images. Note, you should use the 'stable' emulator for arm images for now as it appears we have a bug launching arm in the latest canary release.

**Comment by amiralam0** [comment]
> You can:
> 
> * run arm only images. The performance will not be good and it is generally not recommended.
> * remove  --device /dev/kvm from run.sh and  pass in the `-no-accel` flag and I.e. `./run.sh -no-accel` . This is not offically supported, and the performance will not be great.

how to run the image with this argument ?
i mean where to add this command
