### ISSUE TITLE
Invalid command-line parameter

### ISSUE THREAD

**Issue by Chineye-UTexas** [google/android-emulator-container-scripts#172]
When I run: docker-compose -f js/docker/docker-compose-build.yaml up

I get this error below, that causes the emulator to immediately exit and not run

**emulator_1     | * daemon started successfully
emulator_1     | invalid command-line parameter: =======.
emulator_1     | Hint: use '@foo' to launch a virtual device named 'foo'.
emulator_1     | please use -help for more information
docker_emulator_1 exited with code 1**

**Comment by pokowaka** [comment]
Which steps did you take to create the container?  You must run `emu-docker create` before you can run the docker-compose script.

**Comment by Chineye-UTexas** [comment]
Hi yes, I followed the steps in the README

I ran emu create, it successfully built the image.

Then I ran create-web-contatainer.sh
That was successful.

Then I ran the docker up command, and got those errors.

**Comment by pokowaka** [comment]
Ok, that's not good. Could you perhaps share the log lines that contain 'version:'?  For example:
`docker-compose -f js/docker/docker-compose-build.yaml up` | grep 'version'

It should result in something like this:
```
version: Android emulator version 30.0.22.0 (build_id 6677735) (CL:N/A)
version: launch_script: 0+untagged.201.g3d192e8
version: Pkg.Desc=System Image x86_64 with Google APIs.
version: Pkg.Revision=9
version: Pkg.Dependencies=emulator#28.1.9
version: AndroidVersion.ApiLevel=29
version: SystemImage.Abi=x86_64
version: SystemImage.TagId=google_apis
version: SystemImage.TagDisplay=Google APIs
version: SystemImage.GpuSupport=true
version: Addon.VendorId=google
version: Addon.VendorDisplay=Google Inc.
version:
```

**Comment by Chineye-UTexas** [comment]
Of course:

```
Starting docker_nginx_1         ... done
Recreating docker_emulator_1    ... done
Starting docker_jwt_signer_1    ... done
Recreating docker_front-envoy_1 ... done
emulator_1     | version: Android emulator version 30.0.22.0 (build_id 6677735) (CL:N/A)
emulator_1     | version: launch_script: 0+untagged.210.g8581081.dirty
emulator_1     | version: Pkg.Desc=Android SDK System Image
emulator_1     | version: Pkg.UserSrc=false
emulator_1     | version: Pkg.Revision=4
emulator_1     | version: AndroidVersion.ApiLevel=28
emulator_1     | version: SystemImage.Abi=x86_64
emulator_1     | version: SystemImage.GpuSupport=true
emulator_1     | version: SystemImage.TagId=default
emulator_1     | version: SystemImage.TagDisplay=Default Android System Image
emulator_1     | pulse: (   0.002|   0.000) I: [pulseaudio] sconv_sse.c: Initialising SSE2 optimized conversions.
emulator_1     | 		module.version = "10.0"
emulator_1     | 		module.version = "10.0"
emulator_1     | 		module.version = "10.0"
emulator_1     | 		native-protocol.version = "32"
front-envoy_1  | [2020-07-23 03:29:02.471][6][info][main] [source/server/server.cc:249] initializing epoch 0 (hot restart version=11.104)
emulator_1     | pulse: (   0.012|   0.000) D: [pulseaudio] protocol-native.c: Protocol version: remote 32, local 3
```

**Comment by Chineye-UTexas** [comment]
Hi, I resolved it. it was due to me having rogue syntax in the launch-emulator.sh script above the call to emulator. 

However, I now have this issue: 

`emulator: registered 'boot-properties' qemud service
emulator_1     | emulator: Adding boot property: 'qemu.cmdline' = 'androidboot.logcat=v:* androidboot.consolepipe=qemu_pipe,pipe:logcat'
emulator_1     | emulator: Adding boot property: 'qemu.logcat' = 'start'
emulator_1     | emulator: ERROR: Not enough space to create userdata partition. Available: 2657.250000 MB at /android-home/Pixel2.avd, need 4915.200000 MB.
emulator_1     |
docker_emulator_1 exited with code 1`

**Comment by pokowaka** [comment]
Ok, let me know if we can close this issue.

**Comment by Chineye-UTexas** [comment]
Yes you can close, thank you.

**Comment by serkanalgl** [comment]
Hi all,

I'm getting same issue. Could you please help me how did you fix this issue?

Best Regards,
Serkan
