### ISSUE TITLE
Ambiguous image repository naming

### ISSUE THREAD

**Issue by trevjonez** [google/android-emulator-container-scripts#190]
Given the following invocation within a scripted environment:
```bash
git clone git://github.com/google/android-emulator-container-scripts.git
cd android-emulator-container-scripts
. ./configure.sh
emu-docker licenses --accept
emu-docker -v create --metrics 'stable' 'N google_apis x86'
```

The expected outcome is two images for `N` and `g_apis`, but the default tag naming in [emu_downloads_menu.py repo_friend_name](https://github.com/google/android-emulator-container-scripts/blob/b21ccf47ddc27c63f5027f145a394d76e91c5b10/emu/emu_downloads_menu.py#L167) omits api level which means that for scripted invocations targeting any of `J`,`L`,`N`, or `O` will proceed to build then overwrite the previously created container.

current behavior produces a single image with repo and tag name and overwrites/orphans the previous
```bash
> docker images --format "{{.Repository}}:{{.Tag}}"
n-google-x86:30.0.26
<none>:<none>
debian:stretch-slim
```

desired/expected behavior would produce one for each permutation in the cartesian product set
```bash
> docker images --format "{{.Repository}}:{{.Tag}}"
n-25-google-x86:30.0.26
n-24-google-x86:30.0.26
debian:stretch-slim
```

I have a branch with a potential fix ready and will link that PR back to this issue

**Comment by pokowaka** [comment]
We should probably just switch to API levels, the only concern in that case would be unreleased images that might not have an API level yet.

That way we would have:

- 24-google-x86:xxx
- 25-google-x86:xxx

Would that work? 

This change will require us to republish a set of images.

**Comment by trevjonez** [comment]
yeah that works for me. the the letters don't add anything useful beyond what the api level gives us anyway.

**Comment by trevjonez** [comment]
Ok i added that to the PR. I have it falling back to codename if the api level is empty.
