### ISSUE TITLE
emu-docker create --extra "-http-proxy http://..." gives error: argument --extra: expected one argument

### ISSUE THREAD

**Issue by dmarjanovic** [google/android-emulator-container-scripts#194]
@pokowaka according to the comment https://github.com/google/android-emulator-container-scripts/issues/103#issuecomment-577822626 it should be (or was at some point) possible to pass proxy to emu-docker create like this:

```
(venv) [user@host android-emulator-container-scripts]$ emu-docker create emuzip imgzip --extra "-http-proxy http://a.b.c.d:e"
usage: emu-docker create [-h] [--extra EXTRA] [--dest DEST] [--tag TAG]
                         [--repo REPO] [--push] [--gpu] [--metrics]
                         [--no-metrics] [--start]
                         emuzip imgzip
emu-docker create: error: argument --extra: expected one argument
```

I'm trying to add proxy support in one-time image build process to simplify CI but not sure if possible. Any idea how to fix the error or this is not supported any more?

Thank you
Dragan

**Comment by pokowaka** [comment]
This should work! We must have accidentally broken this.  I will add some tests and make sure this functions again.

**Comment by pokowaka** [comment]
Okay this is odd:

```sh
± emu-docker create canary "Q.*64" --extra "-create a b"                                                                   ⏎ ✹
Parsed all
Downloading system image: google_apis 29 Q x86_64 to 
```

v.s.

```sh
 ± emu-docker create canary "Q.*64" --extra "-http-proxy http://a.b.c.d"                                                    ⏎ ✹
usage: emu-docker create [-h] [--extra EXTRA] [--dest DEST] [--tag TAG] [--repo REPO] [--push] [--gpu] [--metrics] [--no-metrics]
                         [--start]
                         emuzip imgzip
emu-docker create: error: argument --extra: expected one argument
```

v.s.
```sh
± emu-docker create canary "Q.*64" --extra "http-proxy a.b.c.d"                                                            ⏎ ✹
Parsed all
Downloading system image:
```

This seems to suggest something is going wrong with the Python option parser.

**Comment by pokowaka** [comment]
Hypothesis: 

Python parser is treating -http as -h option, causing it not to consider the next section as a parameter.
Escaping it with a `\` will not result in the desired behavior.  As a temporary workaround:

```sh
emu-docker create xx yy --extra "-verbose -http-proxy http://a.b.c.d" 
```

**Comment by pokowaka** [comment]
Related python issues:

- https://bugs.python.org/issue9334
- https://stackoverflow.com/questions/16174992

Looks like adding a space before -h will work too: " -http-proxy http://a.b.c.d.e"
