### ISSUE TITLE
Multi-touch support doesn't work properly

### ISSUE THREAD

**Issue by matoh** [google/android-emulator-container-scripts#208]
When testing an android-emulator ([6837279](https://dl.google.com/android/repository/emulator-linux-6837279.zip)) with a mobile device multi-touch events seems to be not processed properly by the emulator.

I am experiencing issues with not releasing multi-touches properly, and the emulator kept touch on hold, blocking consecutive touches (sometimes multi-touches get processed but seem like some touches are still not released).

I tried to set `force:0` for `touchEnd` events manually when releasing touches, but anyway it didn't fix the problem, sometimes these multi-touches are processed properly but in a while, some touches still kept on hold.

Did you experience the same issues or multi-touches are not supported yet?

**Comment by copiltembel** [comment]
Yes, I'm having the same problem for a long time now. See https://issuetracker.google.com/issues/156318833

**Comment by pokowaka** [comment]
I've updated the internal bug, tracking progress there.

**Comment by matoh** [comment]
@pokowaka I would like to ask you if there is an update regarding this issue?

**Comment by danielmalmq** [comment]
Found out some more info relating to this bug, by sending a touch event with pressure 0 with same identifier as some previously finished event will cause the emu to interpret it as a touch event with pressure. Resulting in a non terminated touch event.

So if events are received out of order from the streaming container this issue will occur

Another minimal way of recreating this issue in java for example:
```
EmulatorControllerGrpc
        .newBlockingStub(ManagedChannelBuilder.forAddress("localhost", 8554).usePlaintext().build())
        .sendTouch(TouchEvent.newBuilder()
                .addTouches(Touch.newBuilder().setIdentifier(0).setX(1).setY(1).setPressure(1))
                .addTouches(Touch.newBuilder().setIdentifier(0).setX(1).setY(1).setPressure(0))
                .addTouches(Touch.newBuilder().setIdentifier(0).setX(2).setY(1).setPressure(0))
                .build());
```

**Comment by matoh** [comment]
@pokowaka did you managed to replicate the issue? Is there some update? Thanks

**Comment by pokowaka** [comment]
We are tracking the issue internally: https://issuetracker.google.com/issues/156318833

**Comment by pokowaka** [comment]
This will be fixed when https://android-review.googlesource.com/c/platform/external/qemu/+/1518422 goes in.

**Comment by pokowaka** [comment]
Emulator builds after https://ci.android.com/builds/branches/aosp-emu-master-dev/grid?head=7017359 will have the change.  Earliest release is expected to be Emulator 30.3.4.
