### ISSUE TITLE
The options for EMULATOR_PARAMS?

### ISSUE THREAD

**Issue by Chineye-UTexas** [google/android-emulator-container-scripts#214]
i am trying to pass them in when I quick run, but I cant seem the understand how to structure it in the script.

Could i have an example, I am trying to possible set the partition size, and no-snapshot, etc.

i.e. run.sh <docker-image> <additional-emulator-params> , what would I place in the second param. I am aware it can be a list

**Comment by Chineye-UTexas** [comment]
Was super obvious, found the params here: 

:~/android-emulator-container-scripts/src/emu/emulator# ./emulator -h

**Comment by mkonkel** [comment]
To be honest I can't see where the list of `EMULATOR_PARAMS` is.
@Chineye-UTexas can u help me plz?

**Comment by ashishnarmen** [comment]
> To be honest I can't see where the list of `EMULATOR_PARAMS` is.
> @Chineye-UTexas can u help me plz?

There are some parameters listed on the [Android Developer User Guide](https://developer.android.com/studio/run/emulator-commandline). 
I tried using `EMULATOR_PARAMS="-camera-back emulated"` but that did not work.
