### ISSUE TITLE
grpc call getStatus() (booted) crashes the emulator

### ISSUE THREAD

**Issue by copiltembel** [google/android-emulator-container-scripts#222]
I'm using a grpc cpp client to connect directly to the emulator. I noticed there's a ```getStatus()``` method which contains a ```bool booted``` element. But when I call it from my client, it crashed the emulator.

Here is a code excerpt:

```c++
grpc::ClientContext context;
context.set_wait_for_ready(true);
google::protobuf::Empty empty;
EmulatorStatus response;
emuController->getStatus(&context, empty, &response);
booted = response.booted(); // emu crashes when calling this
```

Output from the emu:

```
...
emulator: INFO: GrpcServices.cpp:288: Started GRPC server at 0.0.0.0:8878, security: Insecure
emulator: INFO: boot completed
emulator: INFO: boot time 17145 ms
emulator: Increasing screen off timeout, logcat buffer size to 2M.
emulator: Revoking microphone permissions for Google App.
Segmentation fault (core dumped)
```

This did not happen with older versions of the emulator (i.e. 30.0.12.0 (build_id 6466327) works).

I have made a complete example here: https://github.com/copiltembel/android_emulator_grpc_getStatus_crash

**Comment by pokowaka** [comment]
I'm not able to reproduce this with our python test client against head

- Could you share the emulator build this happens on?
- Could you give me access to the sample? 
- Do you happen to have a core dump?

**Comment by copiltembel** [comment]
It seems that I'm only having troubles reproducing it consistently today. There's something in my setup that causes it to crash.

Sorry for the trouble!
