### ISSUE TITLE
web container images

### ISSUE THREAD

**Issue by AlexTrotsenko** [google/android-emulator-container-scripts#256]
In the [medium post](https://medium.com/androiddevelopers/android-emulator-in-a-ci-environment-dd65f63cdcd) it was mentioned, that new _prebuilt_ Android Emulator _Containers_ support  `adb` and `web` access.

Indeed it's very conveniently to run such emulators in docker without installing Python, NodeJS, npm, etc. 

However it's nor clear how to make `web` access working without manually creating web container via [`create_web_container.sh`.](https://github.com/google/android-emulator-container-scripts#running-the-create-script)

Is it possible somehow to achieve it without installing all the these tools? Perhaps there are already some prebuilt containers for providing web access to the emulators (similar to container created for emulators themselves)?

**Comment by pokowaka** [comment]
We currently do not plan to provide a single container to solve this. We mainly provide this as a sample and starting point for those who are interested in more advanced scenarios of deploying the emulator in the cloud.

**Comment by AlexTrotsenko** [comment]
@pokowaka thanks for the information. It's a bit sad to hear this. Having at least basic web container might bring more people into using emulator in the docker and to UI testing in CI in general.
