### ISSUE TITLE
Fail to start web UI to interact with emulator. 

### ISSUE THREAD

**Issue by tandt53** [google/android-emulator-container-scripts#27]
I got error when trying to launch web UI to interact with emulator. Please help to fix it.
Command: `docker-compose -f js/docker/docker-compose.yaml build`

```Building front-envoy
Step 1/6 : FROM envoyproxy/envoy:latest
latest: Pulling from envoyproxy/envoy
16c48d79e9cc: Pull complete
3c654ad3ed7d: Pull complete
6276f4f9c29d: Pull complete
a4bd43ad48ce: Pull complete
ef9506777d3e: Pull complete
2e7ad8d4ceb7: Pull complete
d9e379d45dad: Pull complete
b283a3f5aebc: Pull complete
095fe71f6465: Pull complete
Digest: sha256:a7769160c9c1a55bb8d07a3b71ce5d64f72b1f665f10d81aa1581bc3cf850d09
Status: Downloaded newer image for envoyproxy/envoy:latest
 ---> 72e91d8680d8
Step 2/6 : COPY ./envoy.yaml /etc/envoy/envoy.yaml
 ---> 5bd234bf88da
Step 3/6 : ADD certs/self_sign.crt /etc/cert.crt
 ---> d85d47f62a14
Step 4/6 : ADD certs/self_sign.key /etc/key.key
 ---> 1c22d750f457
Step 5/6 : ADD certs/jwt_secrets_pub.jwks /etc/jwt_secrets_pub.jwks
ERROR: Service 'front-envoy' failed to build: ADD failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder085442460/certs/jwt_secrets_pub.jwks: no such file or directory```

**Comment by 741g** [comment]
Hi, sorry for the breakage. We recently added authentication to allow the web ui to be used from more places easily.

Have you run create_web_container.sh? The readme has instructions on using it to generate the secrets:

https://github.com/google/android-emulator-container-scripts/blob/master/README.md#running-the-emulator-on-the-web

**Comment by pokowaka** [comment]
Let me know if the above mentioned suggestion did not work. The web demo now requires authentication and the create_web_container.sh script will generate all your personal keys and passwords.

**Comment by tandt53** [comment]
Thanks @741g 
Your solution works fine!
