### ISSUE TITLE
emu-docker: command not found

### ISSUE THREAD

**Issue by Grosha** [google/android-emulator-container-scripts#30]
I tried run a command `emu-docker -h` and have a result `emu-docker: command not found`.
All requirements are installed.

Logs after the command `python setup.py install --user`:
`root@autom-android:/home/emulator/android-emulator-container-scripts-master# python setup.py install --user
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing requirements to emu_docker.egg-info/requires.txt
writing emu_docker.egg-info/PKG-INFO
writing top-level names to emu_docker.egg-info/top_level.txt
writing dependency_links to emu_docker.egg-info/dependency_links.txt
writing entry points to emu_docker.egg-info/entry_points.txt
reading manifest file 'emu_docker.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'emu_docker.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/emu
copying build/lib.linux-x86_64-2.7/emu/emu_downloads_menu.py -> build/bdist.linux-x86_64/egg/emu
copying build/lib.linux-x86_64-2.7/emu/docker_device.py -> build/bdist.linux-x86_64/egg/emu
copying build/lib.linux-x86_64-2.7/emu/_version.py -> build/bdist.linux-x86_64/egg/emu
creating build/bdist.linux-x86_64/egg/emu/templates
copying build/lib.linux-x86_64-2.7/emu/templates/Dockerfile -> build/bdist.linux-x86_64/egg/emu/templates
copying build/lib.linux-x86_64-2.7/emu/templates/launch-emulator.sh -> build/bdist.linux-x86_64/egg/emu/templates
copying build/lib.linux-x86_64-2.7/emu/templates/default.pa -> build/bdist.linux-x86_64/egg/emu/templates
creating build/bdist.linux-x86_64/egg/emu/templates/avd
copying build/lib.linux-x86_64-2.7/emu/templates/avd/Pixel2.ini -> build/bdist.linux-x86_64/egg/emu/templates/avd
creating build/bdist.linux-x86_64/egg/emu/templates/avd/Pixel2.avd
copying build/lib.linux-x86_64-2.7/emu/templates/avd/Pixel2.avd/config.ini -> build/bdist.linux-x86_64/egg/emu/templates/avd/Pixel2.avd
copying build/lib.linux-x86_64-2.7/emu/templates/README.md -> build/bdist.linux-x86_64/egg/emu/templates
copying build/lib.linux-x86_64-2.7/emu/__init__.py -> build/bdist.linux-x86_64/egg/emu
copying build/lib.linux-x86_64-2.7/emu/emu_docker.py -> build/bdist.linux-x86_64/egg/emu
byte-compiling build/bdist.linux-x86_64/egg/emu/emu_downloads_menu.py to emu_downloads_menu.pyc
byte-compiling build/bdist.linux-x86_64/egg/emu/docker_device.py to docker_device.pyc
byte-compiling build/bdist.linux-x86_64/egg/emu/_version.py to _version.pyc
byte-compiling build/bdist.linux-x86_64/egg/emu/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/emu/emu_docker.py to emu_docker.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying emu_docker.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying emu_docker.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying emu_docker.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying emu_docker.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying emu_docker.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying emu_docker.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
emu._version: module references __file__
creating 'dist/emu_docker-0+unknown-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing emu_docker-0+unknown-py2.7.egg
removing '/home/groshkka/.local/lib/python2.7/site-packages/emu_docker-0+unknown-py2.7.egg' (and everything under it)
creating /home/groshkka/.local/lib/python2.7/site-packages/emu_docker-0+unknown-py2.7.egg
Extracting emu_docker-0+unknown-py2.7.egg to /home/groshkka/.local/lib/python2.7/site-packages
emu-docker 0+unknown is already the active version in easy-install.pth
Installing emu-docker script to /home/groshkka/.local/bin

Installed /home/groshkka/.local/lib/python2.7/site-packages/emu_docker-0+unknown-py2.7.egg
Processing dependencies for emu-docker==0+unknown
Searching for urlfetch==1.1.3
Best match: urlfetch 1.1.3
Processing urlfetch-1.1.3-py2.7.egg
urlfetch 1.1.3 is already the active version in easy-install.pth

Using /home/groshkka/.local/lib/python2.7/site-packages/urlfetch-1.1.3-py2.7.egg
Searching for tqdm==4.36.1
Best match: tqdm 4.36.1
Processing tqdm-4.36.1-py2.7.egg
tqdm 4.36.1 is already the active version in easy-install.pth
Installing tqdm script to /home/groshkka/.local/bin

Using /home/groshkka/.local/lib/python2.7/site-packages/tqdm-4.36.1-py2.7.egg
Searching for Jinja2==2.10.3
Best match: Jinja2 2.10.3
Processing Jinja2-2.10.3-py2.7.egg
Jinja2 2.10.3 is already the active version in easy-install.pth

Using /home/groshkka/.local/lib/python2.7/site-packages/Jinja2-2.10.3-py2.7.egg
Searching for docker==4.1.0
Best match: docker 4.1.0
Processing docker-4.1.0-py2.7.egg
docker 4.1.0 is already the active version in easy-install.pth

Using /home/groshkka/.local/lib/python2.7/site-packages/docker-4.1.0-py2.7.egg
Searching for console-menu==0.6.0
Best match: console-menu 0.6.0
Processing console_menu-0.6.0-py2.7.egg
console-menu 0.6.0 is already the active version in easy-install.pth

Using /home/groshkka/.local/lib/python2.7/site-packages/console_menu-0.6.0-py2.7.egg
Searching for MarkupSafe==1.1.1
Best match: MarkupSafe 1.1.1
Processing MarkupSafe-1.1.1-py2.7-linux-x86_64.egg
MarkupSafe 1.1.1 is already the active version in easy-install.pth

Using /home/groshkka/.local/lib/python2.7/site-packages/MarkupSafe-1.1.1-py2.7-linux-x86_64.egg
Searching for websocket-client==0.56.0
Best match: websocket-client 0.56.0
Adding websocket-client 0.56.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for requests==2.22.0
Best match: requests 2.22.0
Adding requests 2.22.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for ipaddress==1.0.17
Best match: ipaddress 1.0.17
Adding ipaddress 1.0.17 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for backports.ssl-match-hostname==3.7.0.1
Best match: backports.ssl-match-hostname 3.7.0.1
Adding backports.ssl-match-hostname 3.7.0.1 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /home/groshkka/.local/bin

Using /usr/local/lib/python2.7/dist-packages
Searching for certifi==2019.9.11
Best match: certifi 2019.9.11
Adding certifi 2019.9.11 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for urllib3==1.25.6
Best match: urllib3 1.25.6
Adding urllib3 1.25.6 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for emu-docker==0+unknown`

Do you know where is a problem?

**Comment by 741g** [comment]
Hi, thanks for bringing this up. This may be because we've installed the package to this location:

"Installing emu-docker script to /home/groshkka/.local/bin"

while the dir is not on your PATH.

**Comment by pokowaka** [comment]
Another thing you could try is to run the following:
```sh
source ./configure.sh
```

This will create a virtual environment and activate it for you. This will make sure everything is isolated and you should be able to launch `emu-docker`.

**Comment by dogan-gulcan-zocdoc** [comment]
Thanks! I was able to launch `emu-docker` after;
```bash
source ./configure.sh
```

**Comment by bqbs** [comment]
Delete the `--user` if you run as root.It work for me.
