### ISSUE TITLE
Showing remote emulators in Android Studio

### ISSUE THREAD

**Issue by wjohnson5** [google/android-emulator-container-scripts#303]
hey @pokowaka, any chance the emulator starts shipping with `goldfish-webrtc-bridge` on mac? I'd love to use the '--fwd' arg to show remote emulators in Android Studio ([that is, if i'm reading this right?](https://android.googlesource.com/platform/external/qemu/+/bb6b3e2c2760d7c864c602495a4673695a39b8ff%5E%21/))

**Comment by pokowaka** [comment]
That is a prototype that will not work right now. We are working on moving
Webrtc into the emulator itself with support for both Mac and windows so we
can use remote emulators in studio.

Getting the prototype to work yourself will be non trivial.

**Comment by wjohnson5** [comment]
Awesome, looking forward to it :)

We're actively ramping up our company onto remote emulators, for now using our own frontend built on top of [android-emulator-webrtc](https://github.com/google/android-emulator-webrtc). Android Studio integration would be ideal 👍
