### ISSUE TITLE
Emulator shows only the status:connecting, and after some Minutes disconnect with (gRPC low level error: Http response at 400 or 500 level )

### ISSUE THREAD

**Issue by nahshal** [google/android-emulator-container-scripts#362]
Hallo Team, 

following the steps here: https://source.android.com/docs/automotive/start/avd/cloud_emulator
 I have tried to install the Emulator on a GCP VM with Ubuntu 22, that supports nested Virtualization. and made sure that http/https firewall is allowed for the Instance. 
the emulator and system image used is following: 

- EMU canary 34.1.7 macosx https://dl.google.com/android/repository/emulator-darwin_x64-10965993.zip
- SYSIMG Q android x86_64 29 https://dl.google.com/android/repository/sys-img/android/x86_64-29_r08-linux.zip

I could get the Emulator running and I could also sign in with firebase, but after signing in, I see nothing but the status:connecting and after some Minutes the status is turned to disconnected with the following Error: 
Low level gRPC error: {"message":"Http response at 400 or 500 level).

![Bildschirmfoto 2023-10-25 um 11 22 11](https://github.com/google/android-emulator-container-scripts/assets/4079985/a17adf70-f413-4771-9be2-b7de9dd0fdf9)

![Bildschirmfoto 2023-10-25 um 16 13 10](https://github.com/google/android-emulator-container-scripts/assets/4079985/70b12281-4dcd-41b1-9f09-2f242bef2fa1)

another Problem, I can only reach the Emulator with http://<external-ip> but not with https://<external-ip>

I have tried also to activate turn and everything I found on the Internet, without any Success. By the way, I have not changed any configuration, the only thing I changed is the firebase configuration.

**Comment by nahshal** [comment]
I have solved my Issue, in case any one facing the same Problem:

I have changed the source code of the envoy.yaml to work with https, so I generated new Certificate and uploaded them unter js/docker/cert and then copy then into the project inside the envoy.Dockerfile. 

I also changed the port in envoy.yaml to use 8443 in the sametime, changed this in envoy.Docker and more important in js/src/Apps.js, it is hard coded there with 8080, change it to 8443. Of course, here you would need to allow traffic from VM  for https with port 8443

after that the Emulator was connected and working for png but not showing any video (webRTC). so then follow the Doc to enable the COTURN server and do not forget to allow the UDP traffic from your VM for the turn port that you configured.

and then it should work.

**Comment by nahshal** [comment]
The Configuration you have written is not clear and there is a lot of info missing or not updated.

**Comment by ajaysagar99** [comment]
@nahshal - I need some help with setting this up, I am unable to signin after doing all the configuration. It will be of great help if you can spare some time

**Comment by nahshal** [comment]
@ajaysagar99, you need to check 3 places, 
1. first create new project on firebase and then copy the configuration from setting.
2. Edit the file js/firebase.config in the Emulator Project and add your configuration.
3. in your GCP Account, you need to edit the firebase configuration to match the firebase configuration.

**Comment by ajaysagar99** [comment]
@nahshal - Can you please elaborate more on how you did step 3?

**Comment by nahshal** [comment]
@ajaysagar99,

In your GCP account, go to Credentials, you will find OAuth 2.0 Client IDs.
Web client (auto created by Google Service, go inside and then make sure you insert your URLs inside the Authorised JavaScript origins
something like

URIs 1:  https://<your-project-id>.firebaseapp.com
URIs 2: https://<emulator-domain-url>

also make sure that under 
API keys -->. Set an application restriction  Websites (checked)

**Comment by ajaysagar99** [comment]
@nahshal - Thank you very much! Mine opens in HTTP though and not HTTPS - not sure why

**Comment by ajaysagar99** [comment]
@nahshal - I followed the steps and configured the turn server but I don't see any video. 

Did you find any issues in the documentation?
