### ISSUE TITLE
Getting issue while running docker-compose -f js/docker/docker-compose-build.yaml -f js/docker/development.yaml up command 

### ISSUE THREAD

**Issue by hridhar** [google/android-emulator-container-scripts#369]
Please find the below error.  we had gone through the errors and we saw that some folders are missing then we just created folders and added all the necessary information but still it is showing below error.
Please check and support.
**emulator_1     | pulse: (   0.010|   0.000) D: [pulseaudio] protocol-native.c: Client enabled srbchannel.
emulator_1     | pulse: (   0.010|   0.000) I: [pulseaudio] client.c: Freed 0 "pactl"
emulator_1     | pulse: (   0.010|   0.000) I: [pulseaudio] protocol-native.c: Connection died.
emulator_1     | * daemon started successfully
emulator_1     | emulator:  NVIDIA_VISIBLE_DEVICES=all no_proxy=bosch.com HOSTNAME=5b8c7466fa9a PWD=/android/sdk NVIDIA_DRIVER_CAPABILITIES=graphics,compat32,utility,display HOME=/root https_proxy=http://192.168.100.1:3128 ANDROID_AVD_HOME=/android-home NO_PROXY=bosch.com SHLVL=0 HTTPS_PROXY=http://192.168.100.1:3128 ANDROID_SDK_ROOT=/android/sdk HTTP_PROXY=http://192.168.100.1:3128 http_proxy=http://192.168.100.1:3128 LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PULSE_SERVER=unix:/tmp/pulse-socket _=/usr/bin/env
emulator_1     | emulator: emulator/emulator -avd Pixel2 -ports 5556,5557 -grpc 8554 -no-window -skip-adb-auth -no-snapshot-save -wipe-data -no-boot-anim -shell-serial file:/tmp/android-unknown/kernel.log -logcat *:V -feature AllowSnapshotMigration -gpu swiftshader_indirect -shell-serial file:/tmp/android-unknown/kernel.log -logcat-output /tmp/android-unknown/logcat.log -metrics-collection -qemu -append panic=1
emulator_1     | INFO    | Android emulator version 33.1.24.0 (build_id 11237101) (CL:N/A)
emulator_1     | INFO    | AVD Pixel2 has path /android-home/Pixel2.avd
emulator_1     | INFO    | trying to check whether /android/sdk is a valid sdk root
emulator_1     | WARNING | /android/sdk/system-images/android/x86_64/ is not a valid directory.
emulator_1     | WARNING | emulator has searched the above paths but found no valid sdk root directory.
emulator_1     | PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/android/sdk]!
docker_emulator_1 exited with code 1**

**Comment by hridhar** [comment]
any update

**Comment by hridhar** [comment]
Please update.

**Comment by FaradjSaadana** [comment]
Are you able to run `./create_web_container.sh` correctly ?

**Comment by hridhar** [comment]
Solved
