### ISSUE TITLE
Getting a black screen when using webrtc video

### ISSUE THREAD

**Issue by prohilla** [google/android-emulator-container-scripts#37]
**First of all thanks for open sourcing this. Great work.** 

I was able to set up the project and run it. But accessing video is not working, screenshotting works but as you mentioned it kills the performance. I am getting a black screen instead of video. No error/exception in browser console log or server log. Not sure what's going on. I am running on a GCE instance with public access.

<img width="749" alt="Screen Shot 2019-10-29 at 1 55 44 AM" src="https://user-images.githubusercontent.com/1949934/67752050-7c55ab80-f9ef-11e9-9f27-cb199445ea11.png">

**Comment by 741g** [comment]
If you're running on a gce instance, is the browser we're seeing also running in the same instance or is it on your local machine? For the latter, you'll need to setup TURN servers.

**Comment by pokowaka** [comment]
Could you perhaps share the output of: 

'''sh
docker logs docker_emulator_1 | grep video
'''

This might help us understand what the video bridge is trying to do.

**Comment by prohilla** [comment]
@pokowaka log file this is after running turn server, still getting black screen
[log.txt](https://github.com/google/android-emulator-container-scripts/files/3786817/log.txt)

**Comment by pokowaka** [comment]
It looks like the server is not able to establish a connection to the browser, and no udp path can be established:

From the logs:

```
video: (peerconnection.cc:3737): Changing IceConnectionState 1 => 4 
video: (Participant.cpp:60): OnIceConnectionChange: 4
video: (Participant.cpp:66): Disconnected! Time to clean up
video: (network.cc:927): Connect failed with 99
```

It means that WebRTC was not able to find a path from the gce instance to your browser. Somewhere, someone in the network is not letting the packets through. 

I also noticed that there is no turn server in use:

```
video: (Switchboard.cpp:87): Received: {"from":"d72525b1-87e6-4188-af6a-bd98802f0b86","msg":"{\"start\":\"d72525b1-87e6-4188-af6a-bd98802f0b86\"}"}
video: (Switchboard.cpp:175): Sending {"msg":"{\"start\":{}}","topic":"d72525b1-87e6-4188-af6a-bd98802f0b86"} 
```
 **"{\"start\":{}}", {} should not be empty but have your turn config**

Configuration of a turn server is not something we have yet optimized so it is a bit difficult to do.  You will:

1. Have to figure out how to get a json turn config snippet. If you are using the google's api you can use   a curl command: `curl -s -X POST https://networktraversal.
                 googleapis.com/v1alpha/iceconfig?key=MySec` (MySec is your api key)
2. Create an emulator docker container with the extra config flag for obtaining the json config. For example:

```sh
emu-docker create emuzip imgzip  --extra "-turncfg \"curl -s -X POST https://networktraversal.
                 googleapis.com/v1alpha/iceconfig?key=MySec\""
```

3. Now you should be able to invoke

```sh
./create_web_container.sh
```

If all goes well it should pick up your container with turn enabled.

(Note things get more complicated if you cannot obtain a turn configuration through curl).

**Comment by pokowaka** [comment]
Let me know if we can close this.

**Comment by sujiacong** [comment]
I also encountered this problem

**Comment by fukemy** [comment]
same problem, got audio but remain black screen

**Comment by pokowaka** [comment]
@fukemy  + @sujiacong. We've recently updated the JS to address some race conditions. It could be that you have been experiencing this. To help with debugging could you share:

Which version are you using (more specifically which version of android-emulator-webrtc in package.json). 

From the webpage
- logs from chrome:://webrtc-internals
- Any log messages on the javascript console
- Share the output of docker logs docker_emulator_1 | grep video
