### ISSUE TITLE
emulator failed to start

### ISSUE THREAD

**Issue by MickeyMi** [google/android-emulator-container-scripts#38]
emulator_1     | [    7.604790] init: processing action (encrypt)
emulator_1     | [    7.604790] init: computing context for service10-29 17:06:12.244  1420  1420 I android.hardware.graphics.composer@2.1-service: Registration complete for android.hardware.graphics.composer@2.1::IComposer/default.
emulator_1     | 10-29 17:06:12.320  1416  1416 I ServiceManagement: Removing namespace from process name android.hardware.drm@1.0-service to drm@1.0-service.
emulator_1     | 10-29 17:06:12.325  1416  1416 I android.hardware.drm@1.0-service: Registration complete for android.hardware.drm@1.0::IDrmFactory/default.
emulator_1     |  'exec 2 (/system/bin/vdc)'
emulator_1     | [    7.604790] 10-29 17:06:12.364  1416  1416 I ServiceManagement: Removing namespace from process name android.hardware.drm@1.0-service to drm@1.0-service.
emulator_1     | 10-29 17:06:12.368  1416  1416 I android.hardware.drm@1.0-service: Registration complete for android.hardware.drm@1.0::ICryptoFactory/default.
emulator_1     | init: starting service 'exec 2 (/system/bin/vdc)'...
emulator_1     | [    7.621287] init: SVC_EXEC pid 1430 (uid 0 gid 0+0 context default) started; waiting...
emulator_1     | [    7.640288] init: Service 'exec 2 (/system/bin/vdc)' (pid 1430) exited with status 0 waiting took 0.038637 seconds
emulator_1     | [    7.776307] init: processing action (vold.decrypt=trigger_shutdown_framework)
emulator_1     | [    7.776307] init: processin10-29 17:06:12.425  1414  1414 I android.hardware.camera.provider@2.4-service: Camera provider Service is starting.
emulator_1     | g action (init.svc.zygote=stopped)
emulator_1     | [    7.820269] init: processing action (qemu.logcat=start)
emulator_1     | [    7.820269] selinux: avc:  denied  { set } for property=ro.opengles.version pid=1426 uid=0 gid=0 scontext=u:r:qemu_props:s0 tcontext=u:object_r:opengles_prop:s0 tclass=property_service
emulator_1     | [    7.820269] 
emulator_1     | [    7.820269] init: sys_prop(PROP_MSG_SETPROP2): permission denied uid:0 name:ro.opengles.version
emulator_1     | [    7.902042] type=1400 audit(1572368771.840:5): avc: denied { getattr } for pid=1434 comm="init.ranchu-cor" path="/system/bin/toybox" dev="vda1" ino=581 scontext=u:r:goldfish_setup:s0 tcontext=u:object_r:toolbox_ex0
emulator_1     | [    7.920266] init: processing action (vold.decrypt=trigger_post_fs_data)
emulator_1     | [    7.920266] init: processing action (post-fs-data)
emulator_1     | [    8.020896] healthd: unable to get HAL interface, using defaults
emulator_1     | [    8.050632] healthd: BatteryCurrentNowPath not found
emulator_1     | [    8.050632] healthd: BatteryFullChargeP10-29 17:06:12.542  1414  1414 I vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib/hw/camera.ranchu.so from the current namespace instead.
emulator_1     | ath not found
emulator_1     | [    8.050632] healthd: BatteryCycleCountPath not found
emulator_1     | [    8.050632] healthd: battery l=100 v=5000 t=25.0 h=2 st=2 chg=a
emulator_1     | [    8.076498] vdc: 200 1438 Command succeeded
emulator_1     | [    8.076498] init: init_user0 result: 0
emulator_1     | [    8.076498] init: Command 'init_user0' action=post-fs-data (/init.rc:489) returned 0 took 73.6188ms.
emulator_1     | [    8.100567] init: computing context for service 'exec 3 (/system/bin/tzdatacheck)'
emulator_1     | [    8.110567] init: starting service 'exec 3 (/system/bin/tzdatacheck)'...
emulator_1     | [    8.110567] init: SVC_EXEC pid 1441 (uid 1000 gid 1000+0 context default) started; waiting...
emulator_1     | [    8.148936] init: Service 'exec 3 (/system/bin/tzdatacheck)' (pid 1441) exited with status 0 waiting took 0.046772 seconds
emulator_1     | [    8.252107] type=1400 audit(1572368771.840:5): avc: denied { getattr } for pid=1434 comm="init.ranchu-cor" path="/system/bin/toybox" dev="vda1" ino=581 scontext=u:r:goldfish_setup:s0 tcontext=u:object_r:toolbox_ex0
emulator_1     | [    10-29 17:06:12.668  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::maxFrameBufferAcquiredBuffers retrieved: 3
emulator_1     | 8.252107] type=1400 audit(1572368772.240:6): avc: denied { getattr } for pid=1444 comm="init.ranchu-cor" path="/system/bin/toybox" dev="vda1" ino=581 scont10-29 17:06:12.686  1428  1428 I /system/bin/surfaceflinger: 0
emulator_1     | ext=u:r:goldfish_setup:s0 tcontext=u:object_r:toolbox_exec:s0 tclass=file permissive=0
emulator_1     | [    8.255556] init: Service 'ranchu-setup' (pid 1425) exited 10-29 17:06:12.706  1428  1428 I SurfaceFlinger: SurfaceFlinger is starting
emulator_1     | with status 0
emulator_1     | [    8.722459] init: computing context for service 'mdnsd'
emulator_1     | [    8.731145] init: starting service 'mdnsd'...
emulator_1     | [    8.740602] init: Created socket '/dev/socket/mdnsd', mode 660, user 1020,10-29 17:06:12.738  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncEventPhaseO)
emulator_1     | 10-29 17:06:12.741  1413  1413 I ServiceManagement: Removing namespace from process name android.hardware.audio@2.0-service to audio@2.0-servi.
emulator_1     | 10-29 17:06:12.743  1413  1413 I audiohalservice: Registration complete for android.hardware.audio@2.0::IDevicesFactory/default.
emulator_1     |  group 3003
emulator_1     | 10-29 17:06:12.756  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncSfEventPhaseOffsetNs retrieved: 1000000 (default)
emulator_1     | 10-29 17:06:12.775  1414  1414 D EmulatedCamera_QemuClient: Emulated camera list: 
emulator_1     | 10-29 17:06:12.775  1414  1414 D EmulatedCamera_FakeCamera: Initialize: Fake camera is facing back
emulator_1     | 10-29 17:06:12.776  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasSyncFramework retrieved: 1
emulator_1     | 10-29 17:06:12.776  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with auto, 1.000000, 1.000000
emulator_1     | 10-29 17:06:12.777  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with incandescent, 1.380000, 0.600000
emulator_1     | 10-29 17:06:12.777  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with daylight, 1.090000, 0.920000
emulator_1     | 10-29 17:06:12.777  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with twilight, 0.920000, 1.220000
emulator_1     | 10-29 17:06:12.777  1414  1414 V EmulatedCamera_Device: setWhiteBalanceMode with white balance auto
emulator_1     | 10-29 17:06:12.777  1414  1414 D EmulatedCamera_FakeCamera: Initialize: Fake camera is facing front
emulator_1     | 10-29 17:06:12.778  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with auto, 1.000000, 1.000000
emulator_1     | 10-29 17:06:12.779  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with incandescent, 1.380000, 0.600000
emulator_1     | 10-29 17:06:12.779  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with daylight, 1.090000, 0.920000
emulator_1     | 10-29 17:06:12.779  1414  1414 V EmulatedCamera_Device: initializeWhiteBalanceModes with twilight, 0.920000, 1.220000
emulator_1     | 10-29 17:06:12.779  1414  1414 V EmulatedCamera_Device: setWhiteBalanceMode with white balance auto
emulator_1     | 10-29 17:06:12.779  1414  1414 E EmulatedCamera_Factory: 2 cameras are being emulated. 2 of them are fake cameras.
emulator_1     | 10-29 17:06:12.779  1414  1414 E EmulatedCamera_HotplugThread: createFileIfNotExists: Could not create file '/data/misc/media/emulator.camera.hotplug.0', error: 'Permission denied' (13)
emulator_1     | 10-29 17:06:12.779  1414  1414 E EmulatedCamera_HotplugThread: createFileIfNotExists: Could not create file '/data/misc/media/emulator.camera.hotplug.1', error: 'Permission denied' (13)
emulator_1     | 10-29 17:06:12.780  1414  1414 I CamProvider@2.4-impl: Loaded "Emulated Camera Module" camera module
emulator_1     | 10-29 17:06:12.780  1414  1414 E CamProvider@2.4-impl: setUpVendorTags: Vendor tag operations not fully defined. Ignoring definitions.
emulator_1     | 10-29 17:06:12.780  1414  1414 E CamProvider@2.4-impl: initialize: Vendor tag setup failed, will not be available.
emulator_1     | 10-29 17:06:12.780  1414  1414 V EmulatedCamera_Camera: getCameraInfo
emulator_1     | 10-29 17:06:12.781  1414  1414 V EmulatedCamera_BaseCamera: getCameraInfo
emulator_1     | 10-29 17:06:12.781  1414  1414 V EmulatedCamera_Camera: getCameraInfo
emulator_1     | 10-29 17:06:12.781  1414  1414 V EmulatedCamera_BaseCamera: getCameraInfo
emulator_1     | 10-29 17:06:12.781  1414  1414 V EmulatedCamera_Camera: getCameraInfo
emulator_1     | 10-29 17:06:12.781  1414  1414 V EmulatedCamera_BaseCamera: getCameraInfo
emulator_1     | 10-29 17:06:12.781  1414  1414 V EmulatedCamera_Camera: getCameraInfo
emulator_1     | 10-29 17:06:12.781  1414  1414 V EmulatedCamera_BaseCamera: getCameraInfo
emulator_1     | 10-29 17:06:12.788  1414  1414 I ServiceManagement: Removing namespace from process name android.hardware.camera.provider@2.4-service to provider@2.4-se.
emulator_1     | 10-29 17:06:12.793  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::useContextPriority retrieved: 0 (default)
emulator_1     | 10-29 17:06:12.794  1413  1413 I audiohalservice: Registration complete for android.hardware.audio.effect@2.0::IEffectsFactory/default.
emulator_1     | 10-29 17:06:12.796  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::presentTimeOffsetFromVSyncNs retrieved: 0
emulator_1     | 10-29 17:06:12.798  1414  1414 I android.hardware.camera.provider@2.4-service: Registration complete for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0.
emulator_1     | 10-29 17:06:12.800  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::useHwcForRGBtoYUV retrieved: 0
emulator_1     | 10-29 17:06:12.805  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::maxVirtualDisplaySize retrieved: 0 (default)
emulator_1     | 10-29 17:06:12.812  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::useVrFlinger retrieved: 0 (default)
emulator_1     | 10-29 17:06:12.812  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::maxFrameBufferAcquiredBuffers retrieved: 3
emulator_1     | 10-29 17:06:12.815  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
emulator_1     | 10-29 17:06:12.816  1428  1428 I SurfaceFlinger: Enabling HWC virtual displays
emulator_1     | 10-29 17:06:12.816  1428  1428 I SurfaceFlinger: Disabling Triple Buffering
emulator_1     | 10-29 17:06:12.816  1428  1428 I SurfaceFlinger: SurfaceFlinger's main thread ready to run. Initializing graphics H/W...
emulator_1     | 10-29 17:06:12.816  1428  1428 I SurfaceFlinger: Phase offest NS: 1000000
emulator_1     | 10-29 17:06:12.817  1428  1428 D libEGL  : Emulator has host GPU support, qemu.gles is set to 1.
emulator_1     | 10-29 17:06:12.819  1413  1413 E SoundTriggerHalImpl: couldn't load sound trigger module sound_trigger.primary (No such file or directory)
emulator_1     | 10-29 17:06:12.826  1413  1413 I audiohalservice: Registration complete for android.hardware.soundtrigger@2.0::ISoundTriggerHw/default.
emulator_1     | [    8.830275] type=1400 audit(1572368772.240:6): avc: denied { getattr } f10-29 17:06:12.832  1428  1428 E vndksupport: Could not load /vendor/lib/egl/libGLES_emulation.so from sphal namespace: dlopen failed: librar.
emulator_1     | 10-29 17:06:12.832  1428  1428 E libEGL  : load_driver(/vendor/lib/egl/libGLES_emulation.so): unknown
emulator_1     | or pid=1444 comm="init.ranchu-cor" path="/system/bin/toybox" dev="vda1" ino=581 scontext=u:r:goldfish_setup:s0 tcontext=u:object_r:toolbox_exec:s0 tclass=file permissive=0
emulator_1     | [    8.850494] type=1400 audit(1572368772.820:7): avc: denied { search } for pid=1454 comm="mdnsd10-29 17:06:12.865  1413  1413 I audiohalservice: Registration complete for android.hardware.broadcastradio@1.0::IBroad.
emulator_1     | " name="run" dev="tmpfs" ino=1231 scontext=u:r:mdnsd:s0 tcontext=u:object_r:varru10-29 17:06:12.867  1428  1428 D libEGL  : loaded /vendor/lib/egl/libEGL_emulation.so
emulator_1     | n_file:s0 tclass=dir permissive=0
emulator_1     | 10-29 17:06:12.879  1428  1428 D libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
emulator_1     | 10-29 17:06:12.892  1428  1428 D libEGL  : loaded /vendor/lib/egl/libGLESv2_emulation.so
emulator_1     | 10-29 17:06:12.900  1428  1428 D         : HostConnection::get() New Host Connection established 0xb2fa3f00, tid 1428
emulator_1     | 10-29 17:06:12.907  1428  1428 I SurfaceFlinger: EGL information:
emulator_1     | 10-29 17:06:12.907  1428  1428 I SurfaceFlinger: vendor    : Android
emulator_1     | 10-29 17:06:12.907  1428  1428 I SurfaceFlinger: version   : 1.4 Android META-EGL
emulator_1     | 10-29 17:06:12.907  1428  1428 I SurfaceFlinger: extensions: EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer 
emulator_1     | 10-29 17:06:12.907  1428  1428 I SurfaceFlinger: Client API: OpenGL_ES
emulator_1     | 10-29 17:06:12.907  1428  1428 I SurfaceFlinger: EGLSurface: 8-8-8-8, config=0x2
emulator_1     | 10-29 17:06:12.911  1428  1428 D EGL_emulation: eglCreateContext: 0xb2fa0900: maj 2 min 0 rcv 2
emulator_1     | 10-29 17:06:12.916  1428  1428 D EGL_emulation: eglMakeCurrent: 0xb2fa0900: ver 2 0 (tinfo 0xb2f9ba00)
emulator_1     | 10-29 17:06:12.927  1428  1428 I /system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
emulator_1     | 10-29 17:06:12.928  1428  1428 I SurfaceFlinger: OpenGL ES informations:
emulator_1     | 10-29 17:06:12.928  1428  1428 I SurfaceFlinger: vendor    : Google (Google Inc.)
emulator_1     | 10-29 17:06:12.928  1428  1428 I SurfaceFlinger: renderer  : Android Emulator OpenGL ES Translator (Google SwiftShader)
emulator_1     | 10-29 17:06:12.928  1428  1428 I SurfaceFlinger: version   : OpenGL ES 2.0 (OpenGL ES 3.0 SwiftShader 4.0.0.1)
emulator_1     | 10-29 17:06:12.928  1428  1428 I SurfaceFlinger: extensions: GL_EXT_debug_marker GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_depth24 GL_OES_depth32 GL_OES_element_index_uint GL_OES_texture_float GL_OES_texture_ 
emulator_1     | 10-29 17:06:12.928  1428  1428 I SurfaceFlinger: GL_MAX_TEXTURE_SIZE = 8192
emulator_1     | 10-29 17:06:12.928  1428  1428 I SurfaceFlinger: GL_MAX_VIEWPORT_DIMS = 8192
emulator_1     | 10-29 17:06:12.942  1420  1420 I vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.ranchu.so from the current namespace instead.
emulator_1     | 10-29 17:06:12.977  1419  1419 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
emulator_1     | 10-29 17:06:13.147  1419  1419 I chatty  : uid=1000(system) allocator@2.0-s identical 1 line
emulator_1     | 10-29 17:06:13.156  1419  1419 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
emulator_1     | 10-29 17:06:13.165  1428  1428 D SurfaceFlinger: Set active color mode: HAL_COLOR_MODE_NATIVE (0), type=0
emulator_1     | 10-29 17:06:13.169  1428  1428 D EGL_emulation: eglMakeCurrent: 0xb2fa0900: ver 2 0 (tinfo 0xb2f9ba00)
emulator_1     | 10-29 17:06:13.382  1428  1428 D SurfaceFlinger: shader cache generated - 24 shaders in 209.133926 ms
emulator_1     | [    9.10-29 17:06:13.388  1428  1428 D SurfaceFlinger: Set power mode=2, type=0 flinger=0xb2fc9000
emulator_1     | 387175] init: computing context for service 'bootanim'
emulator_1     | [    9.394186] init: starting service 'bootanim'...
emulator_1     | 10-29 17:06:14.059  1428  1449 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
emulator_1     | 10-29 17:06:14.070  1471  1474 D libEGL  : Emulator has host GPU support, qemu.gles is set to 1.
emulator_1     | 10-29 17:06:14.073  1471  1474 E vndksupport: Could not load /vendor/lib/egl/libGLES_emulation.so from sphal namespace: dlopen failed: library "/vendor/lib/egl/libGLES_emulation.so" not found.
emulator_1     | 10-29 17:06:14.073  1471  1474 E libEGL  : load_driver(/vendor/lib/egl/libGLES_emulation.so): unknown
emulator_1     | 10-29 17:06:14.083  1471  1474 D libEGL  : loaded /vendor/lib/egl/libEGL_emulation.so
emulator_1     | 10-29 17:06:14.084  1471  1474 D libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
emulator_1     | 10-29 17:06:14.097  1471  1474 D libEGL  : loaded /vendor/lib/egl/libGLESv2_emulation.so
emulator_1     | 10-29 17:06:14.111  1471  1474 D         : HostConnection::get() New Host Connection established 0xb1f0c100, tid 1474
emulator_1     | 10-29 17:06:14.118  1419  1419 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
emulator_1     | 10-29 17:06:14.129  1428  1449 D         : HostConnection::get() New Host Connection established 0xb2fde780, tid 1449
emulator_1     | 10-29 17:06:14.178  1365  1365 D TrustyKeymaster: Device received generate_key
emulator_1     | 10-29 17:06:14.178  1365  1365 E TrustyKeymaster: calling trusty_keymaster_call insize 85 msg size 89
emulator_1     | 10-29 17:06:14.241  1365  1365 E TrustyKeymaster: Received 1534 byte response
emulator_1     | 10-29 17:06:14.247  1366  1431 I Cryptfs : Using scrypt with keymaster for cryptfs KDF
emulator_1     | 10-29 17:06:14.495  1471  1474 D EGL_emulation: eglCreateContext: 0xb1f13420: maj 1 min 0 rcv 1
emulator_1     | 10-29 17:06:14.518  1471  1474 D EGL_emulation: eglMakeCurrent: 0xb1f13420: ver 1 0 (tinfo 0xb1f0b0b0)
emulator_1     | 10-29 17:06:15.350  1366  1431 I Cryptfs : Signing safely-padded object
emulator_1     | 10-29 17:06:15.354  1365  1365 D TrustyKeymaster: Device received begin
emulator_1     | 10-29 17:06:15.354  1365  1365 E TrustyKeymaster: calling trusty_keymaster_call insize 1401 msg size 1405
emulator_1     | 10-29 17:06:15.354  1365  1365 E TrustyKeymaster: Received 24 byte response
emulator_1     | 10-29 17:06:15.357  1365  1365 D TrustyKeymaster: Device received update
emulator_1     | 10-29 17:06:15.357  1365  1365 E TrustyKeymaster: calling trusty_keymaster_call insize 280 msg size 284
emulator_1     | 10-29 17:06:15.357  1365  1365 E TrustyKeymaster: Received 24 byte response
emulator_1     | 10-29 17:06:15.358  1365  1365 E TrustyKeymaster: Device received finish
emulator_1     | 10-29 17:06:15.358  1365  1365 E TrustyKeymaster: calling trusty_keymaster_call insize 28 msg size 32
emulator_1     | 10-29 17:06:15.361  1365  1365 E TrustyKeymaster: Received 276 byte response
emulator_1     | 10-29 17:06:15.362  1365  1365 E TrustyKeymaster: here finish at 619 output data length 256
emulator_1     | 10-29 17:06:15.363  1365  1365 E TrustyKeymaster: OK here finish at 627
emulator_1     | 10-29 17:06:15.756  1471  1474 D BootAnimation: BootAnimationShownTiming start time: 11756ms
emulator_1     | 10-29 17:06:15.853  1366  1431 I Cryptfs : Using scrypt with keymaster for cryptfs KDF

**Comment by pokowaka** [comment]
Hi, your logs show that the OS is booting and should be showing the boot animation:

**emulator_1 | 10-29 17:06:15.756 1471 1474 D BootAnimation: BootAnimationShownTiming start time: 11756ms**

Could you share how you are trying to launch and connect to the emulator?

**Comment by MickeyMi** [comment]
I replaced the server and increased the number of CPUs without this problem.

**Comment by NoelOmo** [comment]
Just a quick one @MickeyMi I think I have the same issue that you were experiencing. What was the number of CPUs that you had while the emulator was crashing? And how many did you increase to?

**Comment by MickeyMi** [comment]
Hi
I tried it on the Google cloud. I ca n’t start it with fewer CPU cores. I
tried to add it to 14 cores and it succeeded.

Noel Omondi <notifications@github.com> 于2019年12月9日周一 下午10:56写道：
