### ISSUE TITLE
Either upgrade docker version or downgrade requests version

### ISSUE THREAD

**Issue by bilalba** [google/android-emulator-container-scripts#382]
The requests version>2.30 breaks older versions of docker-py and it was addressed here. https://github.com/docker/docker-py/pull/3257

**Comment by AndrewCEmil** [comment]
Just want to add to this:

When running `emu-docker create stable "P.*x86_64"` or similar, I would get an error "Not supported URL scheme http+docker".

I resolved this error by running `pip install --force-reinstall -v "requests===2.31.0"` inside the venv.
