### ISSUE TITLE
Don't install the recommends

### ISSUE THREAD

**Issue by BraisGabin** [google/android-emulator-container-scripts#43]
It's usually good to execute `apt-get install` with the flag `--no-install-recommends`. I did some tests and we would reduce the size of the images around 130MB. And it improves the build time of the images too.

The problem here is that we are installing less things so it's possible to break something... I think that we should add the flag and test the images because:

- If we are not using those dependencies we don't want them in the image
- If we are using some of them we should be explicit in the Dockerfile

What do you think?

**Comment by pokowaka** [comment]
We've merged your pull requests, let me know if we can close this.

**Comment by BraisGabin** [comment]
I just create the PR to close this one.
