### ISSUE TITLE
Run images on MacOSX

### ISSUE THREAD

**Issue by BraisGabin** [google/android-emulator-container-scripts#46]
I can't run the images created by this repo on my MacBook Pro. I get this error:

```
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
```

As far as I know KVM doesn't exist on MacOSX. Could we use `HAXM` here? How?

**Comment by pokowaka** [comment]
Docker on mac is built on top of a hypervisor itself (https://docs.docker.com/v17.09/docker-for-mac/docker-toolbox/) and does not expose any of the virtualization capabilities to the docker container. It will not be possible to run the emulator with hardware acceleration.

**Comment by BraisGabin** [comment]
Ok, so, should it work with `docker-toolbox`? Or the only option is #21?

**Comment by bhack** [comment]
https://github.com/moby/hyperkit/issues/127

**Comment by pokowaka** [comment]
We will not be able to make this work.
