### ISSUE TITLE
Device is offline with non UI CentOS

### ISSUE THREAD

**Issue by jihunim** [google/android-emulator-container-scripts#48]
Device is offline right after  `adb connect localhost:5555`.

Since I am using non UI CentOS, I cannot make if online.

If I know public IP of the emulator and connect it from my MAC, it would be okay.

**Comment by 741g** [comment]
What's non UI CentOS? That sounds like there's an issue with the version of adb on your system. Could you issue `adb version` on both machines and see if the output is any different?

**Comment by jihunim** [comment]
It is suddenly working with no reason.
