### ISSUE TITLE
Error stream

### ISSUE THREAD

**Issue by Volfskin** [google/android-emulator-container-scripts#58]
Hello, until today building an web container for the Android emulator worked just fine. 
Now I`m having this issue: 
****"upstream** connect error or disconnect/reset before headers. reset reason: connection failure"** , upon accessing localhost in browswer. 

Could you please help me?

**Comment by pokowaka** [comment]
Could you please share the logs from the docker container?

**Comment by pokowaka** [comment]
It looks like there might be an issue with the pulse audio driver after the upgrade to the NVIDIA container. Investigating a solution and looking into adding an e2e test to catch these issues in the future.

**Comment by pokowaka** [comment]
Hmm, pulse audio can go down:

**Comment by pokowaka** [comment]
It's likely that are default pulse daemon.conf has changed, causing exits on idle.

**Comment by Volfskin** [comment]
> Could you please share the logs from the docker container?
> 
> You can retrieve the logs using `docker logs <container-id>`

Hello, due the fact that the issue is not occurring under certain parameters, it was difficult to catch logs. I will asap it happens again. 
The only difference that i have observed in my case  ( dunno if this is relevant , but i will still mention it , maybe it helps ) that when i was trying to connect to emulator from web on localhost from home, it was working. When i have tried to perform the same steps on the office's network , the above issue occured. 
Thank you very much for inspecting this
