### ISSUE TITLE
failed to authenticate to localhost:5555

### ISSUE THREAD

**Issue by jboylee** [google/android-emulator-container-scripts#59]
Why do I get "failed to authenticate to localhost:5555" message after docker-compose command?
```
$ docker-compose -f js/docker/docker-compose-with-adb.yaml up
$ adb connect localhost:5555
failed to authenticate to localhost:5555
$ adb devices
List of devices attached
localhost:5555	unauthorized
```

BUT it is okay below.
```
$ ./run.sh docker_emulator
$ adb connect localhost:5555
$ adb devices
List of devices attached
localhost:5555	device
```

**Comment by pokowaka** [comment]
ADB uses public/private key pairs to authenticate to the emulator. The private key always exists, but the public key does not (at least for newer adb versions). When the emulator launches it will create the public key. 

 In the ./run.sh script we pass in the private key and rely on the emulator to generate the public key.

In the docker-compose script we mount the public key and make it available to the launcher. However, it is very much possible that you do not have the ~/.android/adbkey.pub file. So nothing gets mounted and the emulator creates its own adb key pairs. Causing you to not be able to connect.

The easiest work around for now is to launch the emulator on the host once, which will generate the public key.

**Comment by pokowaka** [comment]
We should probably generate the public key in our emu-docker or create_web_container.sh script.

**Comment by pokowaka** [comment]
You can generate the public key as with the following undocumented command:

    adb pubkey  ~/.android/adbkey > ~/.android/adbkey.pub

**Comment by jcods** [comment]
I have encountered similar problems above.
When executing the following command,It displays the connection connection。
> $docker-compose -f js/docker/docker-compose.yaml up
> $adb connect localhost: 5555
    Connection refused.
>$adb devices
   List of devices attached.

I couldn't find the device,but web access was normal.

> $docker ps

I can see the docker_emulator.

**Comment by jboylee** [comment]
I have still same problem. 

I have ~/.android/adbkey.pub.

**Comment by gilzonme** [comment]
Is this solved?
