### ISSUE TITLE
keyError

### ISSUE THREAD

**Issue by jcods** [google/android-emulator-container-scripts#60]
Thanks a lot of documentation。
When I execute the following command, I get an error.
emu-docker create x86_64-29_r09.zip emulator-linux-5889189.zip --dest docker-src-dir

Traceback (most recent call last):
  File "/test/android-emulator-container-scripts/android-emulator-container-scripts/venv/bin/emu-docker", line 11, in <module>
    load_entry_point('emu-docker', 'console_scripts', 'emu-docker')()
  File "/test/android-emulator-container-scripts/android-emulator-container-scripts/emu/emu_docker.py", line 151, in main
    args.func(args)
  File "/test/android-emulator-container-scripts/android-emulator-container-scripts/emu/emu_docker.py", line 43, in create_docker_image
    device.create_docker_file(args.extra)
  File "/test/android-emulator-container-scripts/android-emulator-container-scripts/emu/docker_device.py", line 163, in create_docker_file
    "cpu": self.sysimg.cpu(),
  File "/test/android-emulator-container-scripts/android-emulator-container-scripts/emu/emu_downloads_menu.py", line 117, in cpu
    return self.ABI_CPU_MAP[self.abi()]
KeyError: ''

**Comment by pokowaka** [comment]
You swapped the parameters for the zip files.

**Comment by jcods** [comment]
Super thanks！

**Comment by jcods** [comment]
When I execute ‘emu-docker create emulator-linux-5889189.zip x86_64-29_r09.zip’
It only performed 10 steps and then stopped

> Creating docker image: aemu:google_apis-29-Q-x86_64-29.2.1.. be patient this can take a while!
> Step 1/27 : FROM alpine AS unzipper
>  ---> 965ea09ff2eb
> Step 2/27 : RUN apk add --update unzip
>  ---> Using cache
>  ---> ef2cc9a3b1c2
> Step 3/27 : COPY emulator-linux-5889189.zip /tmp/
>  ---> Using cache
>  ---> 575817e1ec6a
> Step 4/27 : RUN unzip -u -o /tmp/emulator-linux-5889189.zip -d /emu/
>  ---> Using cache
>  ---> c411a938cc93
> Step 5/27 : FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu18.04 AS emulator
>  ---> 89c25683761b
> Step 6/27 : ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES},display
>  ---> Using cache
>  ---> 41ddf1b87817
> Step 7/27 : RUN apt-get update && apt-get install -y --no-install-recommends     libc6 libdbus-1-3 libfontconfig1 libgcc1     libpulse0 libtinfo5 libx11-6 libxcb1 libxdamage1     libnss3 libxcomposite1 libxcursor1 libxi6     libxext6 libxfixes3 zlib1g libgl1 pulseaudio socat     curl ca-certificates &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
>  ---> Using cache
>  ---> 311a2b415acb
> Step 8/27 : RUN mkdir -p /android/sdk/platforms &&     mkdir -p /android/sdk/platform-tools &&     mkdir -p /android/sdk/system-images &&     mkdir -p /android-home
>  ---> Using cache
>  ---> 3ccb3481f54d
> Step 9/27 : COPY launch-emulator.sh /android/sdk/
>  ---> Using cache
>  ---> 7a176a4df2c9
> Step 10/27 : COPY platform-tools/adb /android/sdk/platform-tools/adb
