### ISSUE TITLE
parameter configuration

### ISSUE THREAD

**Issue by jcods** [google/android-emulator-container-scripts#62]
./run.sh <docker-image-id> <additional-emulator-params>

How to configure the ‘additional-emulator-params’ parameter？thanks.

**Comment by pokowaka** [comment]
You can try:

    ./run.sh <container-id> [param1] [param2] [param3]

or embed the extra params with the --extra option during container creation.  The second option will make sure the extra parameters are passed in when launching the container as part of the web configuration.
