### ISSUE TITLE
adb is installed at the wrong location

### ISSUE THREAD

**Issue by BraisGabin** [google/android-emulator-container-scripts#67]
`adb` should be unzipped in `src/platform-tools/adb` but right now is unzipped at `src/platform-tools/adb/platform-tools/adb`. For this reason the healthy state is always unhealthy.

**Comment by pokowaka** [comment]
That's odd, the unit test should validate correct installation. (See https://github.com/google/android-emulator-container-scripts/blob/master/tests/e2e/test_launch_containers.py)

**Comment by BraisGabin** [comment]
Yeah... that's odd... Could it be a problem with filezip and different implementations? Deppending on the OS? I'm using mac to build the images.

The line: `plzip.extract("platform-tools/adb", dest)` is using `dest` as the base folder to extract the file. So on top of that it's creating `platform-tools/adb`. At least that's what I see in my end...

I created a PR that solves the problem for me... but maybe the problem is more complex...
