### ISSUE TITLE
Test multiple android emulator

### ISSUE THREAD

**Issue by jcods** [google/android-emulator-container-scripts#72]
Is it now possible to support creating multiple different containers? I want to test on multiple android emulator simultaneously.

**Comment by pokowaka** [comment]
You can run as many containers as you wish. You just have to provide a port mapping that the emulator will use. For example you can run multiple containers as follows:

```sh
docker run -e "ADBKEY=$(cat ~/.android/adbkey)"  --device /dev/kvm --publish 5556:5556/tcp --publish 5555:5555/tcp ${IMG_ID1}
docker run -e "ADBKEY=$(cat ~/.android/adbkey)"  --device /dev/kvm --publish 5558:5556/tcp --publish 5557:5555/tcp ${IMG_ID2}
adb connect localhost:5555
adb connect localhost:5557
```

Where IMG_ID1  and IMG_ID2 are the names/id of the images you wish to launch. The import part is to publish the internal container port 5555 and 5556 to an available port.  adb needs to connect to published 5555 port.
