### ISSUE TITLE
Use alternative ports to start emulator

### ISSUE THREAD

**Issue by NoelOmo** [google/android-emulator-container-scripts#73]
I know the docs mention that the emulator scripts will actually use port 80, but I want to run this in an environment in which port 80 is already being used. I have already setup everything, my only issue is when I run `docker-compose -f js/docker/docker-compose.yaml up`, I get the following error:
`ERROR: for front-envoy  Cannot start service front-envoy: driver failed programming external connectivity on endpoint docker_front-envoy_1 (fe2ce6554b4ae3dad06850b1911d1d7791ccc095a43b083322b05a7c2a830381): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use`

Is this actually possible?

**Comment by pokowaka** [comment]
Yes, you are free to setup any port binding you desire. You will have to modify the `docker-compose.yaml` to use a different port mapping.  Look for this section in the `front-envy:`  configuration (line 14):

```yaml
    ports:
      - "80:8080"
      - "443:8443"
      - "8001:8001"
```

You will need to change "80:8080" to "xxx:8080"  where xxx is the port you wish to use and "yyy:8443" for the https endpoint.

Note that the emulator is hosted on https:// and the http (port 80) endpoint simple redirects to https (port 443).  So you probably want to to use a url like "https://localhost:yyyy"

**Comment by NoelOmo** [comment]
Thanks
