### ISSUE TITLE
[question] how Can it show emulator in web?

### ISSUE THREAD

**Issue by huang12zheng** [google/android-emulator-container-scripts#78]
1. ./run.sh 6a674e31b788 #image
> start a emulator
2. adb connect localhost:5555
> connect
3. flutter run
> show ok
4. docker-compose -f js/docker/docker-compose.yaml up
> run a web
5. touch localhost in web

However, I can find flutterApp in brower.
What's wrong with me?

**Comment by pokowaka** [comment]
I'm not sure if I understand what is going wrong. Are you not able to connect to the emulator?

**Comment by huang12zheng** [comment]
sorry for replying so late.

![Screenshot from 2019-12-15 14-24-49](https://user-images.githubusercontent.com/28038074/70858985-109bb380-1f47-11ea-8005-12634d5adf72.png)

my flutter connect to docker 6a674e31b788 , and it run will.
> but I can't see it.

I want show it in web, and, I  `docker-compose -f js/docker/docker-compose.yaml up`
it look like ok

> but I can't see it(flutter demo) still.
