### ISSUE TITLE
Emulator is running but cannot connect to it

### ISSUE THREAD

**Issue by NoelOmo** [google/android-emulator-container-scripts#79]
I have successfully ran the emulator, from the logs, it looks like its booting up just fine. However when, I connect to it via adb connect <ip address>:5555 and then type adb devices, I get the following:
`<IP Address>:5555    offline`

Furthermore, when accessing the emulator through the react website, I can only see a black screen that that does not change to anything no matter how long I wait, see attached screenshot:
![image](https://user-images.githubusercontent.com/11806559/69980898-39cd4480-1542-11ea-9a08-b001809e0650.png)

Anyone know what could be the issue here?

**Comment by NoelOmo** [comment]
Upon furher investigations on the logs, I see that the emulator is stuck on an endless loop of the following message
`emulator_1     | kernel: [ 1372.050438] init: Could not find 'android.hardware.graphics.composer@2.1::IComposer/default' for ctl.interface_start
emulator_1     | kernel: [ 1373.014064] init: Received control message 'interface_start' for 'android.hardware.graphics.composer@2.1::IComposer/default' from pid: 1664 (/system/bin/hwservicemanager)`

Anyone who knows what this means?

**Comment by NoelOmo** [comment]
@pokowaka Any insights on this issue?

**Comment by dmarjanovic** [comment]
I am experiencing similar problem where `adb` cannot connect to emulator after using these 3 commands:
```
(venv)$ emu-docker interactive
(venv)$ docker-compose -f js/docker/docker-compose-with-adb.yaml build
(venv)$ docker-compose -f js/docker/docker-compose-with-adb.yaml up
```
It starts all the 4 containers as expected (`docker_emulator_1`, `docker_front-envoy_1`, `docker_jwt_signer_1`, `docker_nginx_1`), I can see the UI in react website, there is `adbkey.pub` inside emulator container as expected but still cannot authorize emulator and it's not possible to use any `adb` command such is `adb logcat`.

```
$ adb kill-server
$ adb connect localhost:5555
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to authenticate to localhost:5555

$ lsof -i tcp:5037
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
adb     11844 deploy   11u  IPv4 880955      0t0  TCP localhost:5037 (LISTEN)

$ adb devices
List of devices attached
emulator-5554	unauthorized
localhost:5555	unauthorized

$ adb reconnect offline
reconnecting localhost:5555
reconnecting emulator-5554

$ adb devices
List of devices attached
emulator-5554	unauthorized

$ adb logcat
- waiting for device -
```

I've tried AVD/Emulator combos:
- google_apis_playstore-27-O-x86-29.2.11
- google_apis_playstore-28-P-x86_64-29.2.11 
- google_apis_playstore-28-P-x86_64-29.2.1

Linux CentOS 7.4 on MacBook Pro with NVidia drivers installed and KVM enabled.

**Comment by NoelOmo** [comment]
> I am experiencing similar problem where `adb` cannot connect to emulator after using these 3 commands:
> 
> ```
> (venv)$ emu-docker interactive
> (venv)$ docker-compose -f js/docker/docker-compose-with-adb.yaml build
> (venv)$ docker-compose -f js/docker/docker-compose-with-adb.yaml up
> ```
> 
> It starts all the 4 containers as expected (`docker_emulator_1`, `docker_front-envoy_1`, `docker_jwt_signer_1`, `docker_nginx_1`), I can see the UI in react website, there are `adbkey` and `adbkey.pub` both inside emulator container and on the host machine as expected but still cannot authorize emulator and it's not possible to use any `adb` command such is `adb logcat`.
> 
> ```
> $ adb kill-server
> $ adb connect localhost:5555
> * daemon not running; starting now at tcp:5037
> * daemon started successfully
> failed to authenticate to localhost:5555
> 
> $ lsof -i tcp:5037
> COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> adb     11844 deploy   11u  IPv4 880955      0t0  TCP localhost:5037 (LISTEN)
> 
> $ adb devices
> List of devices attached
> emulator-5554	unauthorized
> localhost:5555	unauthorized
> 
> $ adb reconnect offline
> reconnecting localhost:5555
> reconnecting emulator-5554
> 
> $ adb devices
> List of devices attached
> emulator-5554	unauthorized
> 
> $ adb logcat
> - waiting for device -
> ```
> 
> I've tried AVD/Emulator combos:
> 
> * google_apis_playstore-24-N-x86-29.2.11
> * google_apis_playstore-27-O-x86-29.2.11
> * google_apis_playstore-28-P-x86_64-29.2.11
> * google_apis_playstore-28-P-x86_64-29.2.1
> 
> Linux CentOS 7.4 on MacBook Pro with NVidia drivers installed and KVM enabled.

Have you had any chance with this?

**Comment by pokowaka** [comment]
This happens due to a mismatch between the adb key used to authenticate to the container, versus the public key that is made available to the container.

Playstore images require ADB to authenticate, so the proper private and public key must be made available to the system image.  The web container creation script tries to mount ~/.android/adbkey.pub. Some things to try:

- Make sure to use the same user account for creation, as well as running the container.
- Make sure a private adb key exists in ~/.android.(i.e. ~/.android/adbkey). If non exists you can create one with `adb keygen ~/.android/adbkey`

I will look into automating this.

**Comment by pokowaka** [comment]
@dmarjanovic could you make sure that the public/private key pairs inside the container match with the one you use to connect?

Things to try is setting $ADB_VENDOR_KEYS before launching adb (make sure to kill the server first), and have it pointed to the same keys used by the container as yours.

The container launched by js/docker/docker-compose-with-adb.yaml will mount the file ~/.android/adbkey.pub

**Comment by dmarjanovic** [comment]
@pokowaka I think the key pairs were matching when I was checking it the first time but will double check tomorrow again just to be sure. I will check the PR too, thank you.

What works just fine though is this combo:
```
(env) $ emu-docker interactive
(env) $ ./run.sh docker_image_id
```
I guess the docker compose approach does something more or differently to emu image.

**Comment by pokowaka** [comment]
The main difference is that `run.sh` will pass the public adb key into the container via an environment variable, whereas the container will mount the file. More specifically:

[run.sh](https://github.com/google/android-emulator-container-scripts/blob/master/run.sh)
```sh
docker run -e "ADBKEY=$(cat ~/.android/adbkey)" -e "EMULATOR_PARAMS=${PARAMS}" --device /dev/kvm --publish 5556:5556/tcp --publish 5555:5555/tcp ${CONTAINER_ID}
```

v.s. mounting it [docker-compse-with-adb.yaml](https://github.com/google/android-emulator-container-scripts/blob/master/js/docker/docker-compose-with-adb.yaml):

```yaml
secrets:
  adbkey.pub:
    file: ~/.android/adbkey.pub
```

Something with the mounting of the secret must not be working as expected.  Which of the following do you see on the docker logs (after launching):

```sh
docker logs docker_emulator_1 | head -n 20
```

- `Copying key from secret partition` <-- Emulator has and abdkey to its disposable, mismatch between keys. Your private key is not matching the public key that is mounted.
- `Using provided secret` <-- Emulator grabs a key from environment variable, should not happen. 
- `No adb key provided.. You might not be able to connect to the emulator.` <-- There was no public key mounted inside the container, the emulator will create one, you will not be able to connect to playstore images. This means mounting of the secret key failed.

**Comment by pokowaka** [comment]
Sample output on my machine:

```sh
$ docker logs docker_emulator_1 | head -n 15
version: Android emulator version 29.2.10.0 (build_id 6023491) (CL:N/A)
version: launch_script: 0+untagged.106.g9591b96
version: Pkg.Desc=System Image x86 with Google APIs.
version: Pkg.Revision=6
version: Pkg.Dependencies=emulator#28.1.9
version: AndroidVersion.ApiLevel=29
version: AndroidVersion.CodeName=R
version: SystemImage.Abi=x86
version: SystemImage.TagId=google_apis
version: SystemImage.TagDisplay=Google APIs
version: SystemImage.GpuSupport=true
version: Addon.VendorId=google
version: Addon.VendorDisplay=Google Inc.
version: 
Copying key from secret partition
```

**Comment by dmarjanovic** [comment]
@pokowaka 

1. When using `./run.sh docker_image_id` method:
- Sample output on my machine -> `Using provided secret`
- both private and public keys match meaning `adb devices` works perfectly out of the box, I guess [THIS](https://github.com/google/android-emulator-container-scripts/blob/master/emu/templates/launch-emulator.sh#L44-L48) worked nicely

2. When using `web container` (`docker-compose`) method:
- Sample output on my machine -> `Copying key from secret partition`
- private key mismatch (I guess because it copies only the public key [HERE](https://github.com/google/android-emulator-container-scripts/blob/master/js/docker/docker-compose-with-adb.yaml#L33)) meaning if I manually extract/copy private key from emulator image `/root/.android/adbkey` to my host `~/.android/adbkey` then `adb devices` works perfect. Note that `adbkey.pub` is already the same as expected since it's "copied from secret partition".

I guess above is enough to track the cause but answering to your previous questions below:

> Make sure to use the same user account for creation, as well as running the container.
I was doing so.

> Make sure a private adb key exists in ~/.android.(i.e. ~/.android/adbkey). If non exists you can create one with adb keygen ~/.android/adbkey
The pair was already created prior any command here.

>could you make sure that the public/private key pairs inside the container match with the one you use to connect?
Private key mismatch when using method 2. It's the same when using method 1.

>Things to try is setting $ADB_VENDOR_KEYS before launching adb
Not sure how to use this exactly.

>The main difference is that run.sh will pass the public adb key into the container via an environment variable, whereas the container will mount the file
Can you try to month private key too in addition to public key? Somehow it looks like a possible solution since when I copy private key manually from emu image back to host then adb works perfectly on the host.

Please note I haven't tried new PR yet since it's really slow to rebuild all images from scratch.

**Comment by pokowaka** [comment]
> Can you try to month private key too in addition to public key? Somehow it looks like a possible solution since when I copy private key manually from emu image back to host then adb works perfectly on the host.

I'm not sure what happened here. There should not be a private key inside the image. Somehow the emulator must have decided to create a keypair on your behalf.

When the container was restarted it was still there. Likely resulting in a mismatch between the private key inside and outside the container, which in turn would explain the auth failures.  Mounting the private key as a secret partition might be the best option to prevent these types of failures.

**Comment by pokowaka** [comment]
> @pokowaka Any insights on this issue?

Your case looks different. It is possible is that the video bridge is not pushing frames because the emulator window is not changing. The problem might go away by clicking on the black screen a few times.

This is something we will have to fix in the video bridge itself.

**Comment by dmarjanovic** [comment]
Just small addition to above comments and answer to my question:

>Can you try to month private key too in addition to public key?

I've tried and it didn't work. Some unknown key pair ended up in emulator container in the end completely different that those on my host. I noticed that `adbkey.pub` in emulator container contains `@unknown` at the end.

**Comment by pokowaka** [comment]
The @unknown and the end suggests that the emulator decided to create a public key. Normally the emulator:

- Creates a private key on first boot if it doesn't exist.
- Derive the public key from the available private key if it doesn't exist.

**Comment by NoelOmo** [comment]
I have literally tried everything on this thread without any success, I have even tried using a non-google api image in order to start the emulator, but it looks like the device is still stuck on the boot screen. I have attached all my logs from my emulator from the moment I start it. If anyone could have a look and let me know what could possibly be wrong I would really appreciate it.[
[thelogs.txt](https://github.com/google/android-emulator-container-scripts/files/3940011/thelogs.txt)
](url)

@pokowaka 
@741g

**Comment by dmarjanovic** [comment]
@NoelOmo where are you running this, some VM or some Linux on bare metal? Which distro/version? Does it run emu nicely when started from Android Studio? For me it wouldn't boot any image (even from AS) with built-in Linux nouveau drivers for GPU until I installed NVidia drivers for CentOS for this MacBook Pro.

**Comment by NoelOmo** [comment]
I am running this on a CentOS server that is running in a VM , I have not tried running emu with AS as the server does not have a GUI. Also I do not have Nvidia graphics card on the server so Im not sure whether I am supposed to install the drivers. Do you have a Nvidia graphics card on your MBP? Can you share the link to those drivers?

**Comment by pokowaka** [comment]
@NoelOmo  I looked at the logs, you are experiencing a Kernel crash, unfortunately this results in an emulator halt. Could you share the output from `uname -a`? This might give us some guidance around possible kvm kernel issues on guest and host.

**Comment by dmarjanovic** [comment]
@NoelOmo my setup is quite different. I do have NVidia graphic on MacBook Pro but I doubt installing random NVdia driver would help you on your server in VM. I had to install AS since stand alone tools were giving me `wrong ANDROID_SDK_ROOT` error I couldn't solve so I had to install GUI (Gnome) too. In the end I had to go with NVidia drivers since emu wouldn't boot even headless. I do plan to take your approach with GUI-less server in VM in order to move all in cloud and am curious where this thread goes.

**Comment by pokowaka** [comment]
One option we could pursue on our end is not to use the nvidia based base image if this is not explicitly requested. This will result in an image that will not enable hardware acceleration in most cloud environments. 

If you wish to try this yourself you could replace the following lines in the generated Dockerfile or the templated Dockefile:

```diff
-FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu18.04
- ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES},display
+FROM debian:stretch-slim
```

**Comment by dmarjanovic** [comment]
> One option we could pursue on our end is not to use the nvidia based base image if this is not explicitly requested

Making it optional or putting the snippet above in e.g. FAQ is welcome for transparency reasons. Not sure if disabling acceleration fully is the best approach.

**Comment by NoelOmo** [comment]
> @NoelOmo I looked at the logs, you are experiencing a Kernel crash, unfortunately this results in an emulator halt. Could you share the output from `uname -a`? This might give us some guidance around possible kvm kernel issues on guest and host.

Herr is the output from uname -a 
> Linux XXXXXXXXXXXX 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by NoelOmo** [comment]
> One option we could pursue on our end is not to use the nvidia based base image if this is not explicitly requested. This will result in an image that will not enable hardware acceleration in most cloud environments.
> 
> If you wish to try this yourself you could replace the following lines in the generated Dockerfile or the templated Dockefile:
> 
> ```diff
> -FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu18.04
> -ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES},display
> +FROM debian:stretch-slim
> ```

I tried this, now the emulator health status does not go past starting, it crashes very soon after starting it up, I have attached the new logs. The following lines are the last lines before it crashes:

> logcat: 12-09 17:45:58.762  1600  1684 W DeviceHAL: Error from HAL Device in function get_master_volume: Function not implemented
> logcat: 12-09 17:45:58.764  1600  1684 W DeviceHAL: Error from HAL Device in function get_master_mute: Function not implemented
> logcat: 12-09 17:45:58.765  1600  1684 W DeviceHAL: Error from HAL Device in function set_master_volume: Function not implemented
> logcat: 12-09 17:45:58.766  1600  1684 W DeviceHAL: Error from HAL Device in function set_master_mute: Function not implemented
> logcat: 12-09 17:45:58.767  1623  1623 I AudioFlinger: loadHwModu

[crashlogs.txt](https://github.com/google/android-emulator-container-scripts/files/3944774/crashlogs.txt)

**Comment by NoelOmo** [comment]
@pokowaka have you had a chance to look at my new logs and the output from uname -a? 

> Sorry for bombarding you with so many questions

**Comment by pokowaka** [comment]
I'm installing Red Hat Enterprise Linux 7, hopefully this will give some more insights.

**Comment by pokowaka** [comment]
@NoelOmo which red hat release are you using? I might not be able to get the same version as you are using.
