### ISSUE TITLE
sorry for replying so late.

### ISSUE THREAD

**Issue by jeannie22** [google/android-emulator-container-scripts#93]
sorry for replying so late.

![Screenshot from 2019-12-15 14-24-49](https://user-images.githubusercontent.com/28038074/70858985-109bb380-1f47-11ea-8005-12634d5adf72.png)

my flutter connect to docker 6a674e31b788 , and it run will.
> but I can't see it.

I want show it in web, and, I  `docker-compose -f js/docker/docker-compose.yaml up`
it look like ok

> but I can't see it(flutter demo) still.

_Originally posted by @huang12zheng in https://github.com/google/android-emulator-container-scripts/issues/78#issuecomment-565782507_

**Comment by pokowaka** [comment]
ok!
