### ISSUE TITLE
Emulator is not started [UnHealthy Status] :

### ISSUE THREAD

**Issue by elango842003** [google/android-emulator-container-scripts#98]
Environment : Linux andrpoc4-3230633 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Emulator : p-google-x64  29.3.4  02e0994de0a1   24 hours ago  3.73GB
docker ps showing unhealthy status.

Hi There, Thank you for actively making changes. I have been following and trying this script from last year. I am using eBay internal VM's.

I could not figure out why this docker emulator went unhealthy status. if you can point out any pointer would be helpful. let me know if you need any more logs.

**Comment by pokowaka** [comment]
I will investigate if you share the logs.

**Comment by pokowaka** [comment]
One possibility is that there is no private adbkey available in the image. This is an issue I will address shortly.

**Comment by elango842003** [comment]
PFA Docker Log.
[docker.log](https://github.com/google/android-emulator-container-scripts/files/4067855/docker.log)

**Comment by elango842003** [comment]
Added few more docker log.
[docker21.log](https://github.com/google/android-emulator-container-scripts/files/4067960/docker21.log)

**Comment by pokowaka** [comment]
I looked at the logs, it seems that the boot process is still ongoing in docker21.log. Note that in P images the boot process can be long due the a lengthy disk encryption phase.

docker21.log is half way in the boot process.

**Comment by elango842003** [comment]
what is the normal time taken to run the healthy ? Also after saying it healthy still showing the boot up screen.
1. If docker ps showing as healthy can i run build and test to target that device ?
